sourcegraph/docs

docs/cody/capabilities/commands.mdx

Close https://github.com/sourcegraph/cody/issues/2186
Moved from https://github.com/sourcegraph/sourcegraph/pull/59281
There is no `replace` mode in custom command. The correct mode should be `edit`: https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/lib/shared/src/chat/prompts/index.ts?L81
Also remove `inline` mode as inline chat has been removed.

fix: custom commands mode

---

.github/workflows/pr-auditor.yml

This disables the test plan check from PR auditor so that we can re-enable it to check for reviewers, etc. as well as future proof it for any features added to PR auditor. 
When this is merged, I will reenable the pr-auditor GitHub action.

Disables test plan check for this repo

---

docs/admin/audit_log.mdx
docs/admin/deploy/index.mdx
docs/admin/deploy/scale.mdx
docs/admin/executors/deploy_executors_kubernetes.mdx
docs/admin/pings.mdx
docs/admin/repo/auth.mdx

- removed suggestion that customers should select kustomize over helm for Kubernetes based deployments
- small typo fix in k8s executor documentation
- updated a number of links that redirect users to the old https://docs.sourcegraph.com docsite

Deemphasizing Kustomize over Helm and minor doc updates

---

docs/admin/updates/grpc/index.mdx

This updates the gRPC docs to reflect that disabling gRPC is no longer possible with 5.3 and onwards. If you run into issues, people have the option of downgrading to 5.2 (which allows you to toggle gRPC on and off) - which our customer support team can assist with.

grpc: update upgrade guide docs for 5.3

---

docs/code_navigation/explanations/features.mdx
docs/code_navigation/explanations/index.mdx

This adds documentation for `Perform an action` project that was implemented earlier.

doc: add entry for perform an entry

---

docs/dev/background-information/scim_postman_collection.json
docs/versioned/5.2/dev/background-information/scim_postman_collection.json

A couple of json files that are used for reference had dangling commas in them.

small fix for some json files - remove dangling commas

---

src/data/redirects.ts

These are the only two missing redirections. Also fixed the issue with hardcoded anchor.

fix v5.3.0 generated docs redirects

---

docs/cloud/index.mdx

Per [discussion](https://sourcegraph.slack.com/archives/C022SPMNR0W/p1709661124763989) in #discuss-engineering, aligned on language and examples for discussing why latency is not an effective measure for our cloud services.

Add latency section to Cloud FAQ

---

docs/admin/config/site_config.mdx
docs/admin/index.mdx
docs/admin/pings.mdx
docs/admin/subscriptions/index.mdx
docs/cody/clients/enable-cody-enterprise.mdx
docs/cody/core-concepts/cody-gateway.mdx
docs/dev/how-to/cody_gateway.mdx
docs/dev/security/secret_formats.mdx

Some users have gotten Sourcegraph Enterprise license keys confused with Cody Pro subscriptions because the former was also called "Subscriptions" in the user settings area ([example](https://discord.com/channels/969688426372825169/1212987159791800351/1213121019397546024)). The UI will start referring to these as "Enterprise licenses" not "Subscriptions" when https://github.com/sourcegraph/sourcegraph/pull/60911 is merged, to avoid confusion.

rename "Subscriptions" to "Enterprise licenses" to avoid confusion with Cody Pro

---

docs/cody/clients/feature-reference.mdx

- https://app.asana.com/0/1205845687915332/1206816088751898/f

Remove /slash commands on feature parity page

---

docs/admin/access_control/index.mdx
docs/dev/how-to/add_permissions.mdx
docs/dev/how-to/debug_permissions.mdx
docs/dev/how-to/index.mdx

I noticed in the grouping for `dev/how-tos`, we group content for Access Control and Repository permissions together, this PR separates that.
Also @bobheadxi suggested renaming the title of the Access Control docs for adding permissions so it's clear it's about RBAC permissions and not repository permissions.

update documentation for permissions (RBAC and Repository)

---

docs/admin/config/site_config.mdx
docs/admin/pings.mdx
docs/admin/subscriptions/index.mdx
docs/cody/clients/enable-cody-enterprise.mdx
docs/cody/core-concepts/cody-gateway.mdx
docs/dev/how-to/cody_gateway.mdx
docs/dev/security/secret_formats.mdx
docs/versioned/5.2/admin/pings.mdx

Partially revert https://github.com/sourcegraph/docs/pull/125 - see https://github.com/sourcegraph/sourcegraph/pull/61049. In particular #125 introduced some errors about how Cody Gateway properties are evaluated, notably very few Cody Gateway access properties are evaluated from license keys.
While here I also found another error - there's a table indicating the product subscription token is `not derived from a Sourcegraph license key`, but it _is_ derived from the license key, which is how the zero-config Cody mechanism works. I've fixed this in this PR

rename 'Enterprise license' to 'Enterprise subscription'

---

docs/cody/clients/enable-cody-enterprise.mdx

Here's a detailed breakdown of the architecture for a Cody Enterprise Cloud-hosted Cody deployment.

Add dig for SG cloud-hosted deployment

---

docs/dev/how-to/cody_gateway.mdx

There's no real reason to set up another service account user in local dev like we do in production, so just recommend the use of your local admin user.

dev/cody-gateway: just use site-admin access token for CODY_GATEWAY_DOTCOM_ACCESS_TOKEN

---

docs/cody/capabilities/chat.mdx
docs/cody/capabilities/commands.mdx

Slash commands were removed in v1.2.0 of the VS Code Cody extension (Jan 2024), which makes this documentation incorrect and obsolete. See https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1710314656133489 for context.

remove mentions of slash commands

---

src/data/navigation.ts

This adds the tutorials page to the navigation list under "Help & Support"

Add tutorials page to navigation list

---

docs/code-search/types/search-jobs.mdx

Search Jobs is on by default since 5.3.0. Reading the documentation, this is not obvious and customers have been confused about this. This little update should make it more obvious that Search Jobs works out of the box if the bundled blobstore is used.

search jobs: default on

---

docs/code-search/features.mdx
docs/getting-started/github-vs-sourcegraph.mdx

In 5.3 we disabled Smart Search in the UI, so this PR removes references to it
in the current docs (which represent 5.3).
Relates to https://github.com/sourcegraph/sourcegraph/issues/58815

Remove references to smart search

---

docs/code-search/queries/index.mdx
docs/versioned/5.2/code-search/queries/index.mdx

We updated the naming on the toggle to "Keyword Search" before releasing.

Fix typo in keyword search docs

---

docs/code-search/queries/language.mdx

Add a note about `search-content-based-lang-detection`, which was missing from
the docs. It's presented as a "beta" feature because we still have a few
follow-ups to bring it to GA
(https://github.com/sourcegraph/sourcegraph/issues/60676).

Document content-based lang detection

---

src/components/search/Search.tsx
src/components/search/docsearch/DocSearch.tsx

I like to create browser shortcuts to quickly search sites. For the handbook you can do that with this url 
```
https://handbook.sourcegraph.com/#stq=test
```
However, for the docs site, it does not support this (as far as I can tell). But with this change you can do this
```
http://localhost:3000/#q=test
```
This PR adds support for this by having it look for the `#q=` hash param and using that to set the initial query. 
To support this I had to make a couple changes
1. In Search.tsx I extract the hash param if it is present and set the `initialQuery` prop in the `<DocSearch>` component (which was not passed in before)
2. I updated `<DocSearch>`  to automatically open the search dialog if the initialQuery prop is present and I clear the query when the dialog is closed.

Support initiating search from hash url

---

docs/admin/repo/perforce.mdx

The perforce docs listed the experimental features on the top and says they are **needed**. This changes cleans that up doing the following
1. Put experimental features at the bottom
2. Remove language saying they are needed
3. State they have limited support

Clean up experimental feature section of Perforce docs

---

docs/admin/external_service/gerrit.mdx

A customer had this option disabled which causes Sourcegraph to fail cloning the repos. Until we support SSH cloning as well, this setting is required for connecting to Gerrit.

Add note that HTTP clones need to be enabled for Gerrit

---

docs/admin/deploy/docker-single-container/google_cloud.mdx
docs/admin/url.mdx

This version is half a decade old, and no one is using it. Cleaning up to avoid confusion.

chore: Remove hint about Sourcegraph 2.13

---

docs/cody/capabilities/supported-models.mdx
src/data/navigation.ts

Adds a dedicated page under `Cody > Capabilities > supported-models`
Gives a clear layout of which LLMs are supported for chat and completions and for which account types (Free, Pro, Enterprise)

Add dedicated "Supported Models" page

---

src/app/layout.tsx

Add rel=canonical tags to /docs
[SG Issue](https://github.com/sourcegraph/about/issues/6775)
[GitStart Ticket](https://clients.gitstart.com/sourcegraph/ticket/SGM-6775)
- Run the app
- Open browser dev tool
- Verify if the canonical tag is set to `/docs`

SGM-6775 - Add rel=canonical tags to /docs

---

docs/cody/capabilities/supported-models.mdx
docs/cody/clients/install-vscode.mdx
docs/cody/usage-and-pricing.mdx

This PR adds docs changes for the VS Code release on April 3rd. 
- Mentions about Cluade 3 Sonnet as the default LLM model for Cody Free
- Update Supported LLMs docs page
- Update pricing page 
- Mention updates to @-file file handling and fast look up times

Docs for VS Code release April 3rd

---

docs/dev/background-information/wolfi/index.mdx
docs/dev/how-to/wolfi/add_update_images.mdx
docs/dev/how-to/wolfi/add_update_packages.mdx

Switching over to rules_apko in https://github.com/sourcegraph/sourcegraph/pull/60785 will change how some of the wolfi build process works - update the docs with updated instructions.

Update Wolfi docs for rules_apko

---

docs/cody/capabilities/supported-models.mdx

Adds claude 3 models to the list of supported models for enterprise customers and adds a green tick instead of coming soon. 
To be merged after https://github.com/sourcegraph/sourcegraph/pull/61601 and running the SQL query update

Adding new anthropic claude 3 models family to supported models for enterprise customers

---

docs/cody/capabilities/supported-models.mdx
docs/cody/clients/install-jetbrains.mdx
docs/cody/clients/install-vscode.mdx
docs/cody/usage-and-pricing.mdx

This PR adds docs changes for the JetBrains release on April 9th.
- Mentions about Cluade 3 Sonnet as the default LLM model for Cody Free
- Mentions about the functionality to export Chat history as JSON data
- Update Supported LLMs docs page
- Update pricing page

JetBrains April release

---

docs/CHANGELOG.mdx

removing a changelog entry for a feature that didn't go out in 5.3.9104
[Context](https://sourcegraph.slack.com/archives/C05D629GWJK/p1713262306198269)

remove unreleased changelog entry

---

docs/code-search/queries/language.mdx

update language to reflect that and add a link
to instructions from the language page

repo metadata is GA as of 5.1.0

---

docs/admin/pings.mdx

1. Docs update on new pings data:
- RFC
- https://github.com/sourcegraph/sourcegraph/pull/62080
2. Add missing data on Cody providers pings. It existed on the old docs site, data is still reported via pings, so it should probably be mentioned on the pings page. Feel free to push back on this if we intentionally removed this data.

Add Cody Ignore pings

---

docs/code_insights/explanations/administration_and_security_of_code_insights.mdx
docs/code_insights/explanations/current_limitations_of_code_insights.mdx
docs/code_insights/how-tos/Troubleshooting.mdx
docs/code_insights/language_insight_quickstart.mdx
docs/versioned/5.2/code_insights/how-tos/Troubleshooting.mdx

This PR updates the documentation as a follow-up to https://github.com/sourcegraph/sourcegraph/pull/62011 where we introduced new environment variables and improved the performance of language stats insights.

docs: explain language insights and config mechanisms

---

docs/admin/external_service/github.mdx

Doc update for https://github.com/sourcegraph/sourcegraph/pull/62266

Explain `internal` repositoryQuery

---

docs/cli/how-tos/index.mdx
docs/cli/how-tos/managing_access_tokens.mdx

Added a new link to the "Managing access tokens" page in the how-tos directory since there are a couple of access token-related pages here. There may be a better place for this page.

Add Managing access tokens page

---

docs/admin/auth/builtin.mdx
docs/admin/auth/index.mdx

This PR makes some slight tweaks to the docs for builtin auth, and adds some more explanation of the access requests feature, including screenshots.
Test plan:
Content review.

Move builtin auth to separate page and extend content

---

docs/admin/permissions/api.mdx

As part of https://github.com/sourcegraph/sourcegraph/issues/62105
This PR adds an entry to the explicit permissions API docs about sub-repo permissions and how to use them.

Add docs for sub-repo permissions

---

docs/cody/core-concepts/token-limits.mdx

User-defined window for Opus and Sonnet is mentioned in this same doc as 30k but was added as 200k.
The number is mentioned as 30k here too:
https://sourcegraph.com/blog/cody-vscode-1-14-0-release#bigger-and-better-context-windows-to-improve-chat

Update token-limits of claude 3 sonnet and opus

---

docs/admin/config/settings.mdx
docs/admin/config/site_config.mdx

- Changes to the documentation based on:
- Issue: https://github.com/sourcegraph/sourcegraph/issues/36691
- PR: https://github.com/sourcegraph/sourcegraph/pull/60761

docs: move displayLimit field description from admin site config to user settings docs page

---

.github/pull_request_template.md

As part of the discussion about reducing friction when making docs changes, we're proposing removing the requirement for approval before review.
Users creating PRs will still be **prompted** to get approval for changes via this template, but it will not be enforced. Vercel CI passing **will** still be enforced.
* If a user receives approval, the PR is merged as normal.
* If a user doesn't receive approval, the PR will be merged but a ticket will be opened in the [audit trail repo](https://github.com/sourcegraph/sec-pr-audit-trail/issues?q=is:issue) repo which the docs team will be responsible for closing, effectively performing a post-merge review.

Add default PR template to suggest users get reviews

---

docs/getting-started/github-vs-sourcegraph.mdx

This PR removes 2 links that had become stale and led to nonexistent pages.

Remove stale links from CS vs GH page

---

docs/versioned/5.2/admin/deploy/machine-images/aws-oneclick.mdx
docs/versioned/5.2/admin/deploy/resource_estimator.mdx

The PR adds missing resource estimator and awsoneclick docs in version 5.2 folder.

Add Resource Estimator and AWS OneClick docs in version 5.2

---

docs/cody/clients/install-vscode.mdx

Adds documentation for using experimental models with Code for VS Code
Preview: https://sourcegraph-docs-v2-git-tl-experime-f68005-sourcegraph-f8c71130.vercel.app/cody/clients/install-vscode#experimental-models

Add docs for Cody for VS Code experimental models

---

docs/cody/clients/install-vscode.mdx

Adds aspect ratios to the image and videos to prevent [CLS](https://web.dev/articles/optimize-cls), so we can reliably link to a section of the page without it scrolling away from it as elements load.
To generate the image tags I used:
```zsh
images=(
https://storage.googleapis.com/abc.png
https://storage.googleapis.com/def.png
);
for image in "${images[@]}"; do
curl -O $image
filename=$image:t
aspect_ratio=$(file "$filename" | grep -Eo "[[:digit:]]+ *x *[[:digit:]]+" | sed -e 's/ x / \/ /')
echo "<img"
echo "	src=\"$image\""
echo "	alt=\"\""
echo "	style={{ aspectRatio: '$aspect_ratio' }}"
echo "	/>"
done
```

Remove content layout shifts (CLS) from Cody for VS Code install page

---

.gitignore
docs/code_insights/references/incomplete_data_points.mdx

For https://github.com/sourcegraph/sourcegraph/issues/62295
This PR updates the documentation with more tips for very large repositories.
There are difficulties with Code Insights where it may run for a while, and then tell the user that there were incomplete data points. This probably came from very large repositories not being able to compute reasonably fast.
In addition to this documentation update I'm working on giving users more information about which repositories lead to incomplete datapoints: https://github.com/sourcegraph/sourcegraph/issues/62578
---
@sourcegraph/search-platform I poked a bit at the search backend when gathering this info, and would like to get your input if it's accurate, and if there may be other improvements to make complex queries run faster on very large …

docs: extend troubleshooting for very large repositories

---

docs/admin/updates/index.mdx

Sourcegraph releases do not follow semantic versioning. I'm removing a reference that says we do

Remove semantic versioning references from update page

---

next.config.js

This PR adds a redirect script that routes any `sourcegraph.com/docs/v/x.x` to `x.x.sourcegraph.com` subdomains. The root for legacy versions live at: https://github.com/sourcegraph/docs-legacy-versions

Add a redirector script for routing old docs versions to subdomain

---

src/components/VersionSelector.tsx

The PR adds `target="_blank"` attribute to the `VersionSelector` component file that makes old versions open in a new tab and then redirects to a sub-domain.

Add `target= _blank` in Version Selector to make redirect work

---

docs/code_insights/references/incomplete_data_points.mdx

This PR updates the documentation to explain how users can use a new GraphQL field introduced with https://github.com/sourcegraph/sourcegraph/pull/62756 to identify repositories that cause incomplete datapoints.
For https://github.com/sourcegraph/sourcegraph/issues/62295

feat: explain repository identification for incomplete datapoints

---

docs/admin/repo/add.mdx

Part of https://linear.app/sourcegraph/issue/SRC-359/
This PR adds a new section the code host connection troubleshooting page. It clarifies that a code host needs to be accessible over the network in order to sync repositories with it.

docs: code host connections: add "Sourcegraph can't connect to your code host" section to troubleshooting page

---

docs/cody/clients/enable-cody-enterprise.mdx
src/data/redirects.ts

This makes this section a full reference of the ways Cody Enterprise can use models and model providers, instead of just being about 3rd-party options. It's also not clear what "3rd-party" means, since arguably Anthropic and OpenAI models are 3rd-party even when used via Cody Gateway.
Needs to be merged before https://github.com/sourcegraph/cody/pull/4492

clarify docs for supported models and model providers

---

docs/cody/clients/feature-reference.mdx
docs/cody/clients/install-vscode.mdx
docs/cody/use-cases/vsc-tutorial.mdx

See https://github.com/sourcegraph/cody/pull/4506.
This capability is NOT being removed, but it's very rarely used (and only by non-enterprise users) separately. It is almost always used as part of Cody chat, which performs a natural-language search and shows the results in every chat in the context row.

remove mentions of to-be-removed separate Cody natural-language search quickpick UI (prefer using it via chat instead)

---

src/components/ContentTabs.jsx
src/components/MdxComponents.tsx

This PR introduces the ContentTabs component for creating tabbed content in MDX files. The component handles tab switching and URL updates seamlessly without nesting issues.
```
.
├── docs
│   └── cody
│       └── clients
│           ├── index.mdx
│           ├── install-vscode.mdx
│           ├── install-jetbrains.mdx
│           ├── install-neovim.mdx
│           ├── cody-with-sourcegraph.mdx
│           └── enable-cody-enterprise.mdx
```
- For the main tab set, typically in your index file (e.g., code/clients/index.mdx), use the ContentTabs component with the name prop set to 'main'.
- **Example: docs/cody/clients/index.mdx**
``` mdx
<ContentTabs name='main'>
<ContentTab title="VS Code" href="/cody/clients/install-vscode" />
<ContentTab title="JetBrains (beta)" …
```

Added content tabs component for sub-sections

---

docs/cody/capabilities/supported-models.mdx
docs/cody/clients/install-vscode.mdx
docs/cody/core-concepts/token-limits.mdx
docs/cody/usage-and-pricing.mdx

The PRs adds changes to VS Code docs for the new release. Major changes include mentions of Google Gemini 1.5 Pro
and Google Gemini 1.5 Flash as the supported LLM Models for chat and commands.
Updates the:
- Usage and Pricing docs
- VS Code installation docs
- Images showing supported LLMs for Pro tiers
- Supported LLM docs

Add docs changes for VS Code release June 12th

---

tailwind.config.ts

Updated Tailwind font families to use Inter for both Sans and Display. Mono font is not Roboto Mono.

Updating Tailwind font families

---

docs/admin/config/webhooks/incoming.mdx

The instructions talk abotu some Push tickbox, which doesn't exist. This PR clarifies what actually needs to be done.
Closes SRC-387
Test plan:
Review.

Fix docs for bitbucket server webhooks

---

docs/cli/quickstart.mdx

Per the tin: most macOS developers will have Homebrew, and I think they'll prefer installing through Homebrew instead of an unmanaged binary sitting on disk.

Prefer `brew install` on macOS as Homebrew is more ergonomic

---

docs/cody/capabilities/supported-models.mdx
docs/cody/clients/install-vscode.mdx

This PR updates the following:
- Adds mention of Claude Sonnet 3.5 as another supported LLM model for Chat and Commands for Cody Pro VS Code users
- Updates our Supported LLMs docs 
- Mentions that Claude Sonnet 3.5 is the default model for Chat and Commands for Cody Free users
- https://sourcegraph.slack.com/archives/C05AGQYD528/p1718896254676939

Update details about Claude Sonnet 3.5 Model for Pro

---

docs/cody/capabilities/supported-models.mdx
docs/cody/clients/install-vscode.mdx
docs/cody/core-concepts/token-limits.mdx

This PR adds docs changes for VS Code release v1.24.0. Features the following changes:
- Addition of LLM Selection to Free tier
- Update screenshot for LLM selection on Free Tier
- Update our Supported LLMs page

Docs for VS Code release v1.24.0

---

docs/code_monitoring/how-tos/index.mdx
docs/code_monitoring/how-tos/slack.mdx

Closes https://linear.app/sourcegraph/issue/SRCH-521/ensure-slack-notifs-feature-is-documented-and-on-marketing-site

update Slack notifs code monitoring docs, remove beta label

---

docs/admin/scim.mdx

Adding note that the Microsoft SCIM validator will fail, based on notes [here](https://github.com/sourcegraph/sourcegraph/issues/62185#issuecomment-2109617042). 

Update scim.mdx to include known entra Id issue

---

docs/batch-changes/batch-spec-yaml-reference.mdx
docs/batch-changes/create-a-batch-change.mdx
docs/batch-changes/quickstart.mdx

This adds documentation for the new batch spec version.
Relates to https://github.com/sourcegraph/sourcegraph/pull/63613
Closes SPLF-130

batches: document new version field

---

docs/api/stream_api/index.mdx

This documents all supported query parameters and also updates the curl example.
I also removed the "The Stream API is still evolving" banner.

search: update Stream API doc page

---

docs/cody/clients/enable-cody-enterprise.mdx
docs/cody/clients/feature-reference.mdx
docs/cody/clients/install-jetbrains.mdx
docs/cody/clients/install-vscode.mdx

We delayed the release of LLM drop-down from ENT customers. We need to remove mentions from the docs.
- https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1720756890186079

Remove mentions of LLM selection drop down from ENT tier

---

docs/admin/repo/perforce.mdx

We recently added the ability for searching a specific changelist id for a perforce repo. This PR updates the docs to include info on how this works.

chore(Source): Update Perforce docs to include new search feature

---

docs/cody/clients/feature-reference.mdx

PR removes buggy info on Ollama support for ENT. It is only supported on PLG tiers.

Remove Ollama Support from ENT

---

docs/releases.mdx

Customers get confused about our position on how long they should stay on old versions, or which version they should install, when they see mixed signals in our docs and public handbook. Removing the links to install prior versions helps clarify that the paved path is only to install the latest release.

Reduce customer confusion by removing installation links to old releases

---

docs/cody/capabilities/commands.mdx
docs/cody/clients/cody-with-sourcegraph.mdx
docs/cody/clients/feature-reference.mdx
docs/cody/clients/install-vscode.mdx
docs/cody/index.mdx
docs/cody/quickstart.mdx
src/data/navigation.ts

Adds docs for the upcoming Prompts and the Prompt Library.
- https://linear.app/sourcegraph/issue/PROD-125/create-docs-for-prompts-and-prompt-library

Docs for Prompts and Prompt Library

---

docs/legacy.mdx
src/data/versions.ts

The PR removes old versions from the version selector in our docs.

Remove old versions from version selector drop down

---

docs/admin/auth/index.mdx

Fixed typo in the following line: If not set, unliked with GitHub, it defaults to true, allowing any GitLab user with access to your instance to sign up.

Fix typo "unliked" to "unlike"

---

docs/code-search/code-navigation/envvars.mdx

Removes an environment variable that is no longer used as of https://github.com/sourcegraph/sourcegraph/pull/64027

Removes unused `PRECISE_CODE_INTEL_HUNK_CACHE_SIZE` env variable

---

docs/cody/clients/model-configuration.mdx

Some cleanup for this new doc page. I have some general feedback on the design of this doc outside of these changes:
- This doc seems to be written primarily for site admins that are using Cody Gateway, and doesn't address the BYOK ("advanced") configuration options until later in the doc. I think linking to the [Advanced Configuration](https://sourcegraph.com/docs/cody/clients/model-configuration#advanced-configruation) section earlier in the introductory paragraphs would help make this doc easier to navigate for BYOK admins.
- It's unclear whether how [Default Models](https://sourcegraph.com/docs/cody/clients/model-configuration#default-models) works on BYOK instances, or instances where `"sourcegraph": null` is configured. Specifically, how are "suitable alternatives" determined in …

various typos and link fix

---

docs/batch-changes/configuring-credentials.mdx

We now support github apps and can drop the warning that excludes them.

docs(batches): drop github apps exclusion

---

docs/cody/clients/feature-reference.mdx

This PR ships several improvements to our feature parity reference docs for Cody clients:
- Removes column for Neovim
- Remove Web from Autocomplete
- Move Commands, Context Selection, Prompts & Prompt Library under Chat column 
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1723189248829639

Refactor our feature parity reference for Cody clients

---

docs/admin/deploy/docker-compose/index.mdx

Changed docker compose syntax to the new style (docker-compose is deprecated and docker compose should now be used instead)

Update docker compose guide to new syntax

---

docs/code_insights/explanations/search_results_aggregations.mdx

This page was removed in v5.4 for an unknown reason. We currently have a broken link to it; this adds it back to our doc site.

Restore Search Results Aggregations Explanations Page

---

docs/cody/capabilities/autocomplete.mdx
docs/cody/capabilities/supported-models.mdx
docs/cody/clients/install-vscode.mdx

This PR adds docs for the v1.32 Cody VS Code extension release. Adds the following:
- Cody's Autocomplete capabilities with mentions of DeepSeek as the default model
- Smart Apply code additions

Add Cody docs for VS Code v1.32 release

---

docs/cody/clients/install-vscode.mdx

- https://sourcegraph.slack.com/archives/C07CNJTGB3Q/p1724408474932039

Fix broken image in context retrieval

---

docs/cody/clients/enable-cody-enterprise.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1724371821673379?thread_ts=1724349497.587969&cid=C01DXLN3D0T

Add supported model configuration and llm matrix in docs

---

docs/cody/troubleshooting.mdx

This doc update adds an entry faced by customers on IntelliJ IDEs who experience 100% CPU utilization from the Cody agent. Since no fix is out yet, this doc update introduces a quick and easy workaround for users

Add guidance on cody agent cpu utilization

---

docs/cody/clients/feature-reference.mdx

This PR merge feature parity table into one.

Merge feature parity table into one

---

docs/batch-changes/configuring-credentials.mdx
docs/cody/clients/cody-with-sourcegraph.mdx
docs/cody/clients/feature-reference.mdx
docs/cody/clients/install-jetbrains.mdx
docs/cody/clients/install-vscode.mdx
docs/cody/usage-and-pricing.mdx

This PR tackles all the docs changes in the Sourcegraph 5.7 release that are related to Cody. It caters the following projects:
- Cody Web GA
- Removes the Beta label from everywhere we mention
- Add mentions of LLM selector to only ENT users using the new model configuration
- JetBrains Unified Chat UI
- Replace all media with old UI
- Reorder of information based on a similar structure of VS Code docs
- Smart Apply in JetBrains 
- Mentions about Prompts in docs

Docs changes for Cody featuring Sourcegraph v5.7 release

---

docs/admin/config/webhooks/index.mdx
docs/admin/config/webhooks/outgoing.mdx
docs/batch-changes/configuring-credentials.mdx
docs/code_monitoring/how-tos/index.mdx
docs/code_monitoring/how-tos/webhook.mdx

The PR ships docs for the Webhooks GA scheduled to go live with Sourcegraph 5.7 release.
- https://linear.app/sourcegraph/issue/PROD-251/edit-docs-for-code-monitoring-webhooks-to-remove-any-mention-of-beta#comment-8b570d5f

Webhook GA docs for SG 5.7 release

---

docs/cody/clients/enable-cody-enterprise.mdx
docs/cody/clients/feature-reference.mdx

This PR adds docs for @mentioning directories in Cody chat for Enterprise users.

Docs for @-mentioning directories

---

docs/admin/config/batch_changes.mdx

We found out that commits for GHE will be unverified, unless the instance admin enables web commit signing: https://sourcegraph.slack.com/archives/C04MYFW01NV/p1725436182449839?thread_ts=1725378971.454109&cid=C04MYFW01NV
This PR documents this requirement.
For SRCH-883
For SRCH-802

docs(batches): explain web commit signing requirement

---

src/components/search/docsearch/DocSearchModal.tsx

Algolia stores the lvl0 hits as suggested searches. Our docsite currently only has 1 lvl0 (Documentation) causing the searches to be not useful.
As a quick fix, adding "Cody" and "Code Search" as initial suggestions fixes this. Long term, changing how our docs are getting scraped and getting the navbar headers to act as lvl0 is probably preferred.

Fix undefined suggested search results 

---

docs/cloud/private_connectivity_aws.mdx

cloud: update aws private link docs

---

docs/code_insights/explanations/current_limitations_of_code_insights.mdx

This PR adds a callout to guide customers who may have converted their Perforce depots to git but might encounter an issue where code insights are still not available on those depots.

Add callout for perforce repos converted to git

---

docs/cody/clients/model-configuration.mdx

remove references to invalid provide id anthropic-direct

remove references to invalid provide id anthropic-direct

---

docs/code-search/code-navigation/how-to/index_other_languages.mdx

Removed reference to opening an issue in GitHub

Remove reference to opening issue in index_other_languages.mdx

---

docs/cody/clients/install-vscode.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1725655479439459

Fix config in ENT

---

docs/cody/troubleshooting.mdx

Since 1.16.0 we no longer need to enable cody debug it is enabled by default. This updates doc to remove this and also use the export logs command for easier log retrieval

Remove cody.enable step when getting verbose logs and use export logs command

---

docs/batch-changes/configuring-credentials.mdx

docs(batches): update docs for  github app callback

---

docs/cody/capabilities/autocomplete.mdx
docs/cody/capabilities/chat.mdx
docs/cody/capabilities/debug-code.mdx
docs/cody/clients/cody-with-sourcegraph.mdx
docs/cody/clients/index.mdx
docs/cody/clients/install-neovim.mdx
docs/cody/faq.mdx
docs/cody/index.mdx
docs/cody/usage-and-pricing.mdx
docs/cody/use-cases/generate-unit-tests.mdx
src/data/navigation.ts

This PR removes mentions about Neovim from docs since we are not maintaining it.
- https://sourcegraph.slack.com/archives/CNC4YAL1E/p1725892279814699

Remove mentions of Cody for Neovim extension

---

docs/cody/faq.mdx

- Add documentation for using custom API keys with Cody
- Link to the relevant section in the VSCode extension install guide

docs(cody): add documentation for using custom API keys

---

docs/admin/deploy/index.mdx

Again, some simple reworking on our overview page

Reword some confusing wording on deployment landing page

---

docs/admin/deploy/docker-compose/aws.mdx
docs/admin/deploy/docker-compose/azure.mdx
docs/admin/deploy/docker-compose/digitalocean.mdx
docs/admin/deploy/docker-compose/google_cloud.mdx
docs/admin/deploy/docker-compose/index.mdx
docs/admin/deploy/docker-compose/upgrade.mdx
docs/admin/deploy/docker-single-container/aws.mdx
docs/admin/deploy/docker-single-container/digitalocean.mdx
docs/admin/deploy/docker-single-container/google_cloud.mdx
docs/admin/deploy/docker-single-container/index.mdx
docs/admin/deploy/kubernetes/index.mdx
docs/admin/deploy/kubernetes/kustomize.mdx
docs/admin/deploy/machine-images/gce.mdx
docs/admin/deploy/repositories.mdx
docs/admin/external_services/postgres.mdx
docs/admin/external_services/redis.mdx
docs/admin/http_https_configuration.mdx
docs/admin/ssl_https_self_signed_cert_nginx.mdx
docs/admin/updates/grpc/index.mdx
docs/cli/explanations/versioning.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1725413595941599

Find and replace the current version of Sourcegraph with the old entries

---

docs/admin/updates/index.mdx

Missing update parens

---

docs/cloud/private_connectivity_aws.mdx

cloud: update aws private link dr plan

---

docs/cody/capabilities/ignore-context.mdx

Add sunset notice for Cody Ignore.

Add sunset notice for Cody Ignore

---

docs/cody/core-concepts/token-limits.mdx

This was missing before.
Closes https://linear.app/sourcegraph/issue/CODY-3726/whats-our-token-limits-for-35-sonnet

Show Enterprise 3.5 Sonnet token limits

---

docs/CHANGELOG.mdx

This is an automated changelog update for v5.7.2474

Changelog for v5.7.2474

---

docs/cody/faq.mdx

Added "Can Cody answer non-programming questions?" to the FAQ as per customer request

Updated faq.mdx

---

docs/admin/auth/index.mdx

We use the "name" field from the GitHub API response to match the name in alloworgsmap. For example, "Team Name" will work, but "team-name" won't.
"name": "Team Name",
https://docs.github.com/en/rest/teams/teams?apiVersion=2022-11-28#list-teams-for-the-authenticated-user
https://sourcegraph.sourcegraph.com/github.com/sourcegraph/sourcegraph@07ca65aec65a8ce528846277127b061e98a825ee/-/blob/cmd/frontend/internal/auth/githuboauth/session.go?L286

Clarify what name to use in alloworgsmap

---

docs/cli/explanations/env.mdx

Added a little bit more discoverability to our `SRC_HEADER_` section

Make the SRC_HEADER_ env variable a little bit more discoverable

---

src/components/MdxComponents.tsx
src/components/ui/badge.tsx

The `Badge` component can be customized for various use cases. It is for both Markdown and TypeScript files, and we can modify its style by passing props such as `backgroundColor`, `textColor`, `textSize`, and `variant`.
- `variant` (optional): Determines the badge style. Available options are:
- `default` (default)
- `secondary`
- `destructive`
- `outline`
- `backgroundColor` (optional): Custom background color for the badge. Accepts any valid CSS color value.
- `textColor` (optional): Custom text color for the badge. Accepts any valid CSS color value.
- `textSize` (optional): Controls the text size. Available options:
- `text-xs` (default)
- `text-sm`
- `text-base`
- `text-lg`
- `text-xl`
- `text-2xl`
- Additional props such as `className` or other standard HTML attributes are also …

Added badge component

---

docs/cloud/private_connectivity_sourcegraph_connect.mdx

update srcconnect docs

---

docs/cli/explanations/env.mdx

Added note from https://github.com/sourcegraph/src-cli/blob/main/AUTH_PROXY.md

Add in description of using multiple headers env variable

---

docs/integration/open_in_editor.mdx

The editorId property has been updated to editorIds. The use of the editorId property will now result in an error, as it is no longer supported. Updating the configurations to use the new editorIds list format to avoid issues.

Updated editorId Property to editorIds open_in_editor.mdx

---

docs/cody/capabilities/commands.mdx

The docs were incorrect about prompt visibility.

fix documentation of prompt ownership and visibility

---

docs/cody/clients/model-configuration.mdx

Ideally, setting `"cody.enabled": true` in the site config should be sufficient to enable Cody with the default configuration. However, we discovered a bug where this isn’t currently the case. Without specifying the `"completions"` or `"modelConfiguration"` fields, the default Cody setup doesn’t work as expected. This PR updates the code examples on the model configuration page to clarify that the `"cody.enabled": true` field must always be accompanied by either the `"completions"` or `"modelConfiguration"` fields (for more details see https://github.com/sourcegraph/sourcegraph/pull/839).
Although pull request approval is not enforced for this repository in order to reduce friction, merging without a review will generate a ticket for the docs team to review your changes. So if possible, …

Update model config docs

---

docs/cody/clients/install-vscode.mdx

Add docs for Execute with SmartApply

---

docs/cody/core-concepts/cody-gateway.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1728330699075699

Remove mentions for sg-private from Cody Gateway docs

---

docs/cody/troubleshooting.mdx

This update introduces a workaround for web view JCEF for Android Studio which isn't supported out of the box and causes Cody not to start and get stuck on the spinning icon.

Add guidance for Android Studio for JCEF

---

docs/cody/troubleshooting.mdx

This doc update fixes some typos for a recent change and also adds a troubleshooting addition for Windows users having issues logging in.

Fix typos and add guidance for Windows users

---

docs/cody/clients/feature-reference.mdx

add parity ref for CLI and update autocomplete features

---

docs/admin/deploy/docker-compose/google_cloud.mdx

Replaced mention of AWS RDS with Google Cloud SQL on the page for how to install in Google Cloud.
Fixed error

Fix errors

---

docs/admin/telemetry/index.mdx

I know this is our outdated docs page, but it is still linked from a few places and I paused when I saw this

Update description of telemetry events in docs

---

docs/integration/browser_extension/index.mdx

Removed reference to the browser extension being open-sourced.

Removed reference to open source browser extension

---

docs/technical-changelog.mdx

This is an automated changelog update for v5.8.1579

Changelog for v5.8.1579

---

docs/code-search/code-navigation/precise_code_navigation.mdx

Forgot to update this table earlier.

Mark scip-clang as generally available

---

docs/cody/index.mdx

Fix broken links on main Cody docs page.

Fix broken links

---

docs/cli/index.mdx
src/data/navigation.ts

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1728109114565889

Move Cody CLI with the other CLI docs

---

docs/code-search/code-navigation/inference_configuration.mdx

This PR is stacked on top of:
- https://github.com/sourcegraph/docs/pull/721
Matches monorepo PR: https://github.com/sourcegraph/sourcegraph/pull/1170
Fixes [GRAPH-964](https://linear.app/sourcegraph/issue/GRAPH-964/document-guarantees-around-auto-indexing-inference-in-docs-repo)

Document limits for auto-indexing inference

---

docs/admin/repo/perforce.mdx

Add docs for Perforce IP enforcement

---

docs/code-search/code-navigation/inference_configuration.mdx

Fix failed Vercel deployment in production

---

docs/technical-changelog.mdx

This is a quick fix patch associated to https://linear.app/sourcegraph/issue/REL-490/add-semver-version-to-technical-changelog
This addresses feedback that operationally users couldn't find the correct version tag for the release via the new changelog
The devx release tooling will be updated to generate releases of this form in subsequent releases. 
In progress generator fix: https://github.com/sourcegraph/devx-service/pull/284

Quick fix technical changelog v5.8.1579

---

docs/cody/clients/feature-reference.mdx
docs/cody/clients/install-visual-studio.mdx
docs/cody/index.mdx
src/data/navigation.ts

Docs for Visual Studio extension for Cody.

Add docs for Visual Studio

---

docs/admin/search.mdx

Adds details around the implied fork:no and archived:no search results to search considerations page. This may need to be updated if/when these implied values are removed. 
See Linear comment [here](https://linear.app/sourcegraph/issue/SRCH-1305/morgan-stanley-repo-not-showing-up-in-search-results-unless-specified#comment-161dd719)

Add fork:no and archived:no as search considerations

---

docs/technical-changelog.mdx

Backfill the old changelogs to be in accordance with the introduction of the canonical name policy: https://sourcegraph.com/docs/releases
See: https://github.com/sourcegraph/devx-service/pull/284#issuecomment-2442864646

chore(changelog): backfill the releases, including captialization

---

docs/cody/capabilities/commands.mdx

Doc updates to explain draft prompts.

Doc updates to explain draft prompts

---

docs/technical-changelog.mdx

.mdx files crash when `{` characters are not escaped. 
Also fix capitalization and remove "patch 0" as this goes against our convention. 
Closes: [REL-507: Fix errors on supported release notes links](https://linear.app/sourcegraph/issue/REL-507/fix-errors-on-supported-release-notes-links)

Fix(docs): fix character escape in .mdx file

---

docs/technical-changelog.mdx

Patch 0 isn't needed and is not part of our official naming scheme. Removing these manually now with followup on the source issue later.

fix(rel): remove patch suffix

---

README.md

Update README for preview links

Update README for preview links

---

docs/cody/capabilities/chat.mdx
docs/cody/clients/cody-with-sourcegraph.mdx

Update docs for LLM selection on web

---

docs/technical-changelog.mdx

One last run at Canonical Names (Backfill)
See internal conv: https://sourcegraph.slack.com/archives/C02E4HE42BX/p1730917823118489?thread_ts=1730801659.955189&cid=C02E4HE42BX

chore(release): One last run at Canonical Names (Backfill)

---

docs/admin/config/private-network.mdx

updated `NO_PROXY` ENV service list and added `worker` to list of services that might require `HTTP_PROXY` configuration

updated NO_PROXY list and accounting for worker service

---

docs/admin/monorepo.mdx

There are quite a few other links which should be updated which I will look into later. Given this repository is now frozen, it might make sense to host this script in the docs repository?

Point git-stats link to sourcegraph-public-snapshot

---

docs/admin/code_hosts/go.mdx
docs/admin/code_hosts/non-git.mdx
docs/admin/deploy/kubernetes/index.mdx
docs/admin/executors/deploy_executors_terraform.mdx
docs/admin/external_services/postgres.mdx
docs/admin/how-to/dirty_database.mdx
docs/admin/how-to/dirty_database_pre_3_37.mdx
docs/admin/http_https_configuration.mdx
docs/admin/postgres.mdx
docs/admin/ssl_https_self_signed_cert_nginx.mdx
docs/code-search/code-navigation/how-to/adding_lsif_to_workflows.mdx
docs/code-search/code-navigation/search_based_code_navigation.mdx
docs/releases.mdx

I noticed we still have lots of links to our private repository. These links won't work for people outside of the sourcegraph organisation, so we update them to point to the public snapshot repository.
Note: there are other types of links we should probably update, especially around mentioned issues. Those are not tackled in this commit.

all: update links to sourcegraph blobs to public snapshot

---

docs/admin/code_hosts/github.mdx

Follow up to (this ticket)[https://sourcegraph.zendesk.com/agent/tickets/20672]. We don't specify that the PAT needs to be Classic, so I added a <callout> to make it more clear.

Specify the need for classic PAT for indexing outside org's private repos

---

docs/cody/core-concepts/token-limits.mdx

Hackathon - Token Limits

---

docs/cody/index.mdx

Fix broken links in Features table on main Cody homepage.

Fix broken links in Features table

---

docs/admin/postgres12_end_of_life_notice.mdx

adds proposed customer comms from [this doc](https://docs.google.com/document/d/19m7YAaPxgxw44xCZytjVulkFjU9C42CwycT3zDi_IY8/edit?pli=1&tab=t.0) for easier sharing with customers

adds PGSQL12 EOL notice in markdown format

---

docs/admin/updates/automatic.mdx
docs/admin/updates/docker_compose.mdx
docs/admin/updates/kubernetes.mdx
docs/admin/updates/server.mdx

This PR updates and reformats the Release Notes for the deployment repos. Adding warnings about the v5.10.0 postgres version upgrades and its impact on database upgrades, and reformating and cleaning up the old version release notes.
@Chickensoupwithrice

Release Notes 5.10.0

---

src/components/Toc.tsx
src/components/icons/Globe.tsx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1733262288956719

Add Sourcegraph website icon on docs

---

docs/admin/postgres12_end_of_life_notice.mdx

Add more clarification to the reasoning behind the suggested Postgres backup

chore(rel): add to backup warning on postgres EOL notice

---

docs/batch-changes/quickstart.mdx

fix: remove surplus space

---

docs/admin/updates/docker_compose.mdx
docs/admin/updates/kubernetes.mdx
docs/admin/updates/server.mdx
docs/technical-changelog.mdx

This is just a little embellishment on technical changelog and upgrade notes explaining the autoupgrade path workaround for db drift and also warning customers to skip past v5.10.0 release

chore(rel): warning to skip 5.10.0 release

---

docs/code-search/queries/examples.mdx

Updated regex example to use another repo as sourcegraph/sourcegraph is no longer available in .com instance

Changed regex example to use any github.com repo with regex search

---

src/components/search/Search.tsx
src/data/search.ts

This PR makes two key improvements to our Algolia search implementation:
1. Increases Maximum Results
- Added maxResultsPerGroup parameter to Algolia search component
- Increased limit from default to 20 results per group
- Improves search experience by showing more relevant matches
2. Configuration Refactoring
- Moved Algolia credentials (appId, indexName, apiKey) to centralized searchMetadata config
- Improves maintainability by consolidating search settings in one location
- Makes configuration updates more manageable
Manually after merge

feat(search): increase Algolia search results and externalize config

---

docs/notebooks/notebook-sharing.mdx
docs/notebooks/quickstart.mdx

Notebooks have been disabled on dotcom for over a year now. This removes references to public notebooks from our docs.

chore: remove references to public notebooks

---

docs/admin/deploy/kubernetes/configure.mdx

- **Add documentation for k8s secrets**

k8s Secrets Documentation

---

docs/technical-changelog.mdx

Customer feedback shows that the changelog entry for [1863](https://github.com/sourcegraph/sourcegraph/pull/1863) was not sufficient, so added more to it.

Clarify changelog entry for PR 1863

---

docs/admin/audit_log.mdx

Updates to the information for Audit Logging

Audit Logging Updates

---

docs/cody/enterprise/completions-configuration.mdx
docs/cody/enterprise/model-config-examples.mdx

Closes https://linear.app/sourcegraph/issue/PRIME-658/add-small-warning-to-aws-bedrock-docs-that-access-token-configuration

Update Amazon Bedrock auth

---

docs/technical-changelog.mdx

The sourcegraph/sourcegraph repo is now private, so all links to it are 404 for anyone not logged in to GitHub as a Sourcegraph employee. Knowing the PR is useful for Sourcegraph internally, but including a link that doesn't resolve is not useful for customers, and possibly detrimental.
The format of the PR non-link we settled on is `(PR #1234)`
Before:
- remove 5.10 deprecation dates on out of band migrations [#1996](https://github.com/sourcegraph/sourcegraph/pull/1996)
After:
- remove 5.10 deprecation dates on out of band migrations `(PR #1996)`

Remove all sourcegraph/sourcegraph PR links from the technical changelog

---

docs/admin/external_services/postgres.mdx
docs/admin/postgres.mdx
docs/admin/updates/index.mdx

This PR updates some of our surface information about PG upgrades as well as cleans up some eager suggestions of the automatic upgrade upgrade path. 
It removes references of support for PG12 instead suggesting that we currently only support 16. This was intentional to trim the docs rather than threading out a lot of specific information about Sourcegraph versions.

chore(release): pg 16 update to docs

---

docs/admin/config/index.mdx
docs/admin/config/network-filtering.mdx

This adds documentation on how to configure the `ExternalClient`'s denylist. Previously undocumented, but useful for self-hosting customers.

docs: external denylist configuration 

---

docs/admin/deploy/kubernetes/index.mdx

fixed broken numbering in the top section and rewrote some of the sentences for better clarity

updated overview section

---

docs/technical-changelog.mdx

Update broken links pointing to the kustomize deployment in the technical changelog.

fix(docs): Update broken links for kustomize deployment

---

docs/admin/config/private-network.mdx
docs/admin/config/site_config.mdx
docs/admin/deploy/docker-compose/configuration.mdx
docs/admin/deploy/docker-compose/index.mdx
docs/admin/deploy/docker-compose/operations.mdx
docs/admin/deploy/kubernetes/configure.mdx
docs/admin/deploy/kubernetes/index.mdx
docs/admin/deploy/scale.mdx
docs/admin/observability/alerts.mdx
docs/admin/observability/opentelemetry.mdx
docs/admin/observability/tracing.mdx
docs/admin/observability/troubleshooting.mdx

Centralizing, deduplicating, and correcting information about HTTP traces from multiple different pages into two primary pages specifically about Tracing and OpenTelemetry, then minimizing the content on the deployment / config pages to link back to these two, only leaving the deployment-type-specific details on the pages for each deployment-type.

Cleaning up docs for HTTP traces

---

docs/admin/deploy/kubernetes/azure.mdx
docs/admin/deploy/kubernetes/configure.mdx
docs/admin/deploy/kubernetes/index.mdx
docs/admin/deploy/kubernetes/kustomize.mdx
docs/admin/observability/opentelemetry.mdx
docs/admin/observability/tracing.mdx

Fixing broken links and spelling

Cleanup tracing docs

---

docs/admin/config/network-filtering.mdx

This adds documentation about the new allowlist for "untrusted" external connections, released in 5.11.

security: add allowlist documentation

---

docs/admin/observability/metrics.mdx

Specifying the details needed for customers to secure their Grafana container.

Adding Grafana authentication information

---

docs/admin/observability/metrics.mdx

Clarifying Grafana reinitialization process with customized dashboards

---

docs/releases.mdx
docs/technical-changelog.mdx

This is an automated changelog update for v5.10.3940

Changelog for v5.10.3940

---

README.md
docs.config.js
docs/cody/capabilities/commands.mdx
docs/cody/capabilities/supported-models.mdx
docs/legacy.mdx
src/data/versions.ts

Docs working branch for Sourcegraph Dec release

---

docs/batch-changes/batch-spec-cheat-sheet.mdx

The original snippet has some issues:
The loop will not handle spaces correctly and may misinterpret the path.
The entire string is treated as one entity due to the quotes, leading to incorrect processing.
Updated the loop handling in the script to correctly process file paths by switching from space-delimited to newline-delimited entries. This ensures the handling of paths with spaces or special characters. Added IFS=$'\n' for proper splitting and quoting of paths in the loop for safety.
Spaces in file names

Update batch spec search result looping example

---

docs/cody/clients/install-cli.mdx

A couple customers are getting confused and using both env vars and cody auth login to authenticate with the CLI leading to undesirable effects. This change adds emphasis for customers getting started with CLI

Adding emphasis to steps

---

docs/notebooks/index.mdx

Remove sourcegraph.com links to notebooks

---

docs/cody/clients/install-vscode.mdx

Update models example json

---

docs/cody/clients/install-vscode.mdx

The changes introduce support for the OpenAI provider in the Cody VS Code extension configuration, along with additional configuration options for input and output token sizes, and provider-specific options. This provides more flexibility and options for users when configuring their Cody integration.

feat(docs): add additional configuration options

---

src/components/PreCodeBlock.tsx

We only conditionally replace this _if_ there is a version number in the
code block, because this breaks syntax highlighting.
This is kind of a cheap hack, and we should really be replacing the
strings with version numbers further upstream before they get broken
into syntax highlighting chunks, that way we get to keep both working
version numbers, as well as syntax highlighting.
I tried messing around with contentlayer to replace these strings further upstream, but I couldn't figure it out within my timeboxed session. Hence leaving this PR as it is, because it's fairly important that correct version numbers be displayed and copied by our customers.
You will need to get your PR approved by at least one member of the Sourcegraph team. For reviews of docs formatting, styles, and component …

Fix: Version numbering automatically updates again

---

docs/releases.mdx
docs/technical-changelog.mdx

This is an automated changelog update for v5.11.2732

Changelog for v5.11.2732

---

docs/code-search/types/search-jobs.mdx

This is based on internal feedback that the documentation doesn't describe how to consume the results.
Test plan:
N/A

search jobs: mention download button

---

docs/code-search/features.mdx

Inserted "that" into "find go functions take" within `docs/docs/code-search/features.mdx`.

docs: add missing word to rectify sentence fragment

---

docs/admin/deploy/docker-single-container/index.mdx

Relates to [REL-491](https://linear.app/sourcegraph/issue/REL-491/postgres-sourcegraph-server-aka-single-image-handles-postgres-16)
I think we should not support auto-migration of the database to pg16, since single container is not production capable deployment type, and the customers using it are explicitly trials.

Add a warning that auto-migrate to pg16 is not supported.

---

docs/cody/core-concepts/cody-gateway.mdx

Remove space causing markdown link to render improperly

Remove space in markdown link on cody concepts page

---

docs/admin/search.mdx

The defaults were changed in https://github.com/sourcegraph/zoekt/pull/850.
Test plan:
N/A

search-jobs: update defaults

---

docs/admin/deploy/kubernetes/index.mdx

This is particularly for the helm chart, since a customer was asking
about this. Docs applied from @marcleblanc2's recommendation in the
[linear thread](https://linear.app/sourcegraph/issue/REL-638/configure-aws-rds-databases-for-tls-connections-in-helm-chart)

fix: mention pgsslmode in the docs for external db

---

docs/admin/deploy/docker-single-container/index.mdx

Completes documentation for a [PR](https://github.com/sourcegraph/sourcegraph/pull/2711)

feat: documentation for upgrading the single server container image to postgresql16

---

docs/code-search/code-navigation/precise_code_navigation.mdx
src/data/navigation.ts

The Writing an Indexer page is linked from the Precise Code Nav page.
It doesn't make sense to link it from the overall Nav with the label
'Indexers' because the 'Indexers' title makes it seems like the page
will describe the available indexers.

chore: Remove 'Indexers' entry from side menu

---

docs/technical-changelog.mdx

Add callout in technical changelog for all versions that upgrade Postgres.

chore(docs): add callout for database upgrades in TC

---

docs/admin/deploy/docker-compose/aws.mdx

Remove incorrect customer advisement to not use docker compose and instead use an install script or machine images

chore(docs): remove incorrect customer redirect in aws docker

---

docs/admin/deploy/docker-compose/digitalocean.mdx

Remove incorrect customer advisement to not use docker compose and instead use an install script or machine images

chore(docs): remove incorrect customer redirect in do docker

---

docs/admin/deploy/docker-compose/digitalocean.mdx
docs/admin/deploy/docker-compose/google_cloud.mdx

Remove incorrect customer advisement to not use docker compose and instead use an install script or machine images

chore(docs): remove incorrect customer redirect in gcp docker

---

docs/admin/deploy/docker-compose/azure.mdx
docs/admin/deploy/docker-compose/digitalocean.mdx
docs/admin/deploy/docker-compose/google_cloud.mdx

Remove incorrect customer advisement to not use docker compose and instead use an install script or machine images

chore(docs): remove incorrect customer redirect in azure docker

---

docs/admin/deploy/docker-compose/aws.mdx

Remove another warning telling customers not to use docker compose in a part of the docs that customers would already be running or have chosen docker compose.

chore(docs): remove another warning for docker

---

src/middleware.ts

- https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1737745261526189

Fix redirects issue

---

docs/admin/auth/index.mdx

This is no longer hidden behind a feature flag

Remove section about modal feature flag that is no longer relevant

---

docs/admin/deploy/machine-images/aws-ami.mdx

Add Sourcegraph AWS account IDs to docs for easier customer verification when pulling AMI images.

chore(docs): Add AWS account IDs for AMI publishing

---

docs/admin/deploy/machine-images/aws-ami.mdx

Change AMI docs to reference AWS AMI dynamic sizing that is no longer strictly tied to T-Shirt sizes and pre-defined EC2 instance sizes

chore(docs): Note dynamic AWS sizing

---

docs/admin/external_services/object_storage.mdx
docs/code-search/types/search-jobs.mdx

Updating our existing external object storage documentation to cover both use cases (precise index upload and search jobs). This PR is mostly structural reorganization of the existing content spread across two doc pages for improved readability/ discoverability.

consolidated instructions for configuring external object storage

---

docs/admin/how-to/index.mdx
docs/admin/how-to/postgres_12_to_16_drift.mdx
docs/admin/postgres.mdx
docs/admin/updates/docker_compose.mdx
docs/admin/updates/kubernetes.mdx

This doc adds a troubleshooting doc to aid admins that encounter any of the PG12 to PG16 drift, and also embellishes our documentation surrounding entrypoint upgrade advisements for 5.10.0 through 6.0.0 versions

sourcegraph 6 aware upgrade docs

---

docs/cody/capabilities/auto-edit.mdx

The updated callout message provides more details on the current experimental rollout of the auto-edit feature, including the limited access for Enterprise Starter (Cody Pro) and Enterprise users on Cody Gateway. This change aims to set clearer expectations around the feature's availability.

feat(docs): update auto-edit availability details

---

docs/api/stream_api/index.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1738199819192569

Fix broken link in Stream API docs

---

docs/cody/capabilities/agentic-chat.mdx

fix web browser bolding

---

docs/admin/updates/index.mdx

Fix broken link to Postgres EOL docs

chore(docs): fix broken link to PG EOL

---

docs/admin/code_hosts/gitlab.mdx

It's not clear from reading that this config supports endpoints other than the `/projects` endpoint. This attempts to clarify.
[Related thread](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1738623269376519)
Rendered:

Clarify accepted values for projectQuery

---

docs/cli/how-tos/fetch_sboms.mdx
docs/cli/how-tos/index.mdx
docs/cli/how-tos/verify_container_signatures.mdx

Add documentation for verifying container signatures using `src signature verify`, as introduced in https://github.com/sourcegraph/src-cli/pull/1143.
Also update SBOM documentation to align with the signature verification docs.
- https://sourcegraph-docs-git-will-container-6ad7d6-sourcegraph-f8c71130.vercel.app/docs/cli/how-tos/verify_container_signatures
- https://sourcegraph-docs-git-will-container-6ad7d6-sourcegraph-f8c71130.vercel.app/docs/cli/how-tos/fetch_sboms

Add documentation for verifying container signatures

---

docs/admin/faq.mdx

This update adds directions on how a customer can setup external monitoring using their own Grafana instance.

Add guidelines on how to use external monitoring

---

docs/admin/code_hosts/github.mdx
docs/admin/code_hosts/gitlab.mdx
docs/admin/code_hosts/index.mdx

- https://sourcegraph.slack.com/archives/C079SAU0E72/p1738779930968759

Add callouts to codehost connections docs

---

docs/admin/code_hosts/gerrit.mdx

Gerrit does not require admin credentials, only credentials of a user that can access the required repositories.
Gerrit connections also support cloning via SSH using `gitSSHCredential` like other code hosts.

Update Gerrit docs to remove admin requirement and SSH limitation

---

docs/admin/repo/perforce.mdx

Labels perfore permissions as a beta feature. 

Add a beta mark for Perforce permissions feature

---

docs/admin/config/private-network.mdx

- Revise overview section for clearer explanation of private networks
- Enhance certificate management section with step-by-step instructions
- Update validation steps with clear expected outcomes

docs: improve private network configuration guide tone and readability

---

docs/cody/capabilities/auto-edit.mdx

- https://sourcegraph.slack.com/archives/C022SPMNR0W/p1739380291727409

Update instructions on enabling auto-edit

---

docs/cody/capabilities/supported-models.mdx
docs/cody/faq.mdx

Add clarification around deepseek model and data processing.

Add clarification around deepseek model

---

docs/admin/config/private-network.mdx

This change adds a nuanced item where some customers may need to add an asterisk when using proxies in their override file.

Add callout for instances where NO_PROXY requires an asterisk

---

docs/api/graphql/search.mdx

Update graphql search doc.mdx

---

docs/cody/troubleshooting.mdx
docs/cody/usage-and-pricing.mdx

Clarifying wording to highlight fair usage better.
Test plan: n/a

Clarify wording for fair usage

---

src/components/mdx/Callout.tsx
src/components/mdx/CustomLink.tsx

Callout UI Improved

---

docs/cody/capabilities/prompts.mdx

- https://linear.app/sourcegraph/issue/PROD-493/prompt-templates-editor-moves-current-context-to-mentions-menu-ga-gtm

Context selection for prompts

---

docs/code-search/code-navigation/precise_code_navigation.mdx

Adding an info box to encourage users to first index their repos locally to ensure they work.

Add info box recommending indexing locally first

---

baseai/memory/docs/index.ts
docs-chatbot.md
src/app/api/chat/route.relevancy.ts
src/app/api/chat/route.ts

Add improvements to our chatbot

---

docs/technical-changelog.mdx

This is an automated changelog update for v6.1.2889

Changelog for v6.1.2889

---

docs/cody/troubleshooting.mdx

Update troubleshooting.mdx to include how to debug slowness

---

docs/cody/clients/cody-with-sourcegraph.mdx
docs/cody/clients/install-jetbrains.mdx
docs/cody/clients/install-visual-studio.mdx
docs/cody/clients/install-vscode.mdx

- https://sourcegraph.slack.com/archives/C073U3KE5DK/p1741621076245189?thread_ts=1741620952.558899&cid=C073U3KE5DK
- https://sourcegraph.slack.com/archives/C073U3KE5DK/p1741621922839019

Fix banner and icons in Cody clients docs

---

docs/admin/code_hosts/github.mdx

I didn't see any mention in the docs that GitHub apps automatically create an incoming webhook. 

Add note about webhook setup for Gitub Apps

---

docs/batch-changes/configuring-credentials.mdx

feat: update docs for fine-grained-access tokens

---

docs/admin/deploy/kubernetes/index.mdx
docs/admin/how-to/upgrade-postgres-12-16-builtin-dbs.mdx

closes REL-807
https://linear.app/sourcegraph/issue/REL-807/generate-issue-for-helm-doc-update-regarding-version-targeting

chore(release): Clarify helm MVU warning about postgres version upgrade procedure 

---

docs/batch-changes/create-a-batch-change.mdx

- https://linear.app/sourcegraph/issue/TM-56/docs-april-2025-batch-changes-title-based-search

Docs for title-based search in Batch Changes

---

docs/batch-changes/rebasing-changesets.mdx
src/data/navigation.ts

Updating the docs for the new changeset rebase functionality
@MaedahBatool: Would you take this PR and merge it into the 6.2 branch

docs: rebase changesets

---

docs/batch-changes/faq.mdx

This PR introduces a section that could potentially be asked by customers in the future about automating batch changes with code host runners. This section offers general guidance on how to approach it.

FAQ callout for using runners with Sourcegraph

---

src/data/redirects.ts

Moshin discovered a broken link: https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1743515921995509
This PR adds a redirect to the right content.

fix: add redirect for admin deploy executors

---

docs/releases.mdx

This PR adds Sourcegraph 6.1 Patch 5 (March 2025) to the list of currently supported versions in the releases documentation. It also aligns column spacing in the unsupported versions table for better readability.

chore(rel): add missing patch release

---

docs/technical-changelog.mdx

Fix formatting for code block in changelog

chore(rel): fix formatting for changelog

---

docs/index.mdx
src/data/navigation.ts

Notebooks have been deprecated and are disabled by default. This removes them from the main navigation and removes a few incoming links to notebooks on index pages. This does not remove the notebooks pages so that customers can still search the docs for notebooks pages, just cannot browse to them.

chore: remove notebooks from main navigation and outlines

---

docs/technical-changelog.mdx

Unify capitalization for changelog bullets

fix(rel): unify changelog caps

---

docs/cody/capabilities/agentic-chat.mdx

Remove specific model versions from agentic chat docs

---

docs/admin/permissions/api.mdx

Just a small note clarifying that if no sub-repo permissions have been set for a repository, that repository is treated as not having sub-repo permissions enabled.

Add a note explaining that no sub-repo perms = sub-repo perms disabled

---

docs/code-search/types/search-jobs.mdx

Adds a table to document the ENVs we added in
https://github.com/sourcegraph/sourcegraph/pull/4975
Test plan:
N/A

Search Jobs: document new ENVs

---

docs/admin/auth/saml/azure_ad.mdx

Make it really clear that Azure AD is the same thing as Entra

Update docs for Entra ID  to reference Azure Active Directory

---

docs/admin/postgres12_end_of_life_notice.mdx

This change introduces a nuanced callout where typically customers can use the most recent version of migrator when performing an MVU but to upgrade to 5.10 they explicitly need to use the 5.10 migrator image, otherwise the database upgrade will fail.

Callout on using the correct image for 5.10 upgrade

---

docs/code-search/code-navigation/syntactic_code_navigation.mdx
src/data/navigation.ts

Syntactic indexing public doc

---

docs/batch-changes/tracking-existing-changesets.mdx

I performed some testing on the actions available for imported changesets in Batch Changes. I was able to do the following: 
- **Select Action -> Create Comment:** Batch Changes added the same comment to all of my changesets.  On the Bulk Operation tab, the action indicated it was completed. I confirmed on GitHub that all PRs had the new comment on them. 
- **Select Action -> Merge Changesets:** Batch Changes merged all my changesets into main. On the Bulk Operation tab, the action indicated it was completed. I confirmed that these actions were successfully reflected on GitHub, as all the PRs were merged into main.
- **Select Action -> Close Changesets:** Batch changes closed all my changesets on GitHub. On the Bulk Operation tab, it said completed. I confirmed that these actions were …

Added documentation for tracking changesets' actions 

---

docs/admin/how-to/remove-repo.mdx

We now automatically reclaim disk space for deleted repos, and this debug endpoint no longer exists.
Fixes SRC-1263

docs: remove manual repo data purge section

---

docs/code-search/working/search_contexts.mdx

- https://linear.app/sourcegraph/issue/SRCH-1874/gtm-pm-creating-gtm-materials-definition-of-done-for-search-contexts

Default Search Context for Admins

---

docs/admin/updates/kubernetes.mdx

The service is no longer needed. Corresponding helm chart update: https://github.com/sourcegraph/deploy-sourcegraph-helm/pull/671
Test plan: n/a

Add upgrade info for 6.4 repo updater removal

---

README.md
docs.config.js
docs/code-search/compare-file-filtering.mdx
docs/code-search/features.mdx
docs/code-search/working/search_contexts.mdx
docs/cody/capabilities/chat.mdx
docs/cody/capabilities/supported-models.mdx
docs/legacy.mdx
src/data/versions.ts

This is the docs working branch for SG version 6.3 release.

Docs working branch for Sourcegraph 6.3 release

---

docs/analytics/index.mdx

Removing language around self-hosted vs cloud analytics to align with product roadmap

Remove self-hosted analytics language

---

docs/admin/permissions/index.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1747127214487429

Add Azure DevOps to supported codehosts docs

---

docs/cody/clients/feature-reference.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1747245285490519

Add auto-edit in feature parity reference docs

---

docs/releases.mdx
docs/technical-changelog.mdx

This is an automated changelog update for v6.3.2692

Changelog for v6.3.2692

---

docs/code-search/code-navigation/precise_code_navigation.mdx

- fixes a couple of 404 broken links on the precise indexing doc page
- remove reference to auto-dependency indexing which relies on [package code hosts](https://github.com/sourcegraph/docs/pull/724)

fix missing links and remove reference to auto-dependency indexing

---

docs/api/graphql/index.mdx

Remove link to old Sourcegraph repo

---

docs/admin/deploy/docker-compose/configuration.mdx
docs/admin/deploy/kubernetes/configure.mdx
docs/admin/deploy/without_service_discovery.mdx

INDEXED_SEARCH_INDEXERS was added in a previous release but I missed to document it properly which caused unexpected log spam for customers using docker and failed pods for customers on K8S without service discovery.

search: document INDEXED_SEARCH_INDEXERS

---

docs/cody/enterprise/model-config-examples.mdx
docs/cody/enterprise/model-configuration.mdx

Documents the new `openaicompatible` model configurations supported as part of https://linear.app/sourcegraph/issue/CORE-1019/enablement-ga-self-hosted-models-additional-openai-compatible

modelconfig: document new OpenAI-compatible configurations

---

docs/admin/config/authorization_and_authentication.mdx

See https://github.com/sourcegraph/sourcegraph/pull/5504 for more details, the previous approach has been deprecated by Microsoft and no longer works.
Closes SRC-1300.
Test plan: Ran through this process locally and ended up with working perms syncing.

azure-devops: Adjust docs to cover new Entra OAuth apps

---

docs/integration/bitbucket_server.mdx

See https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1747950678213499?thread_ts=1747950304.392389&cid=C05EMJM2SLR

remove code nav from bitbucket extension docs

---

docs/admin/audit_log.mdx
docs/admin/config/advanced_config_file.mdx
docs/admin/enterprise_getting_started_guide/index.mdx
docs/admin/executors/deploy_executors_binary.mdx
docs/admin/executors/deploy_executors_binary_offline.mdx
docs/admin/executors/deploy_executors_kubernetes.mdx
docs/admin/executors/firecracker.mdx
docs/admin/how-to/dirty_database_pre_3_37.mdx
docs/admin/how-to/monorepo-issues.mdx
docs/admin/how-to/redis_configmap.mdx
docs/admin/pings.mdx
docs/admin/repo/perforce.mdx
docs/admin/security_event_logs.mdx
docs/cloud/index.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1747943923325639

Remove mentions of old sg/sg repo V2

---

docs/code-search/types/deep-search.mdx
src/data/navigation.ts

This PR adds a page for Deep Search, a new experimental feature going into EAP with the 6.4 release.

Add deep search page to docs

---

docs/admin/audit_log.mdx

Update docs to reflect audit log format changes.

add audit log changes

---

docs/code-search/types/deep-search.mdx

This PR adds examples for Deep Search model configuration on GCP Vertex. This already works, it just wasn't documented.

Add GCP Vertex description to Deep Search

---

docs/cody/capabilities/supported-models.mdx

Updated the doc to correct that Cody-gateway users can also use Claude model and how site admins can enable it

Updated the doc to correct that Cody-gateway users can also use Claude model and how site admins can enable it

---

docs/cody/enterprise/completions-configuration.mdx
docs/cody/enterprise/model-config-examples.mdx

This adds documentation for AWS Bedrock latency improvements that were added in Sourcegraph v6.5 as part of https://linear.app/sourcegraph/issue/CORE-1020/enablement-ga-self-hosted-models-aws-bedrock-improved-latency

add Sourcegraph v6.5 AWS Bedrock latency documentation

---

docs/analytics/index.mdx

Big update for lots of recent changes to SG Analytics

Update Sg Analytics metrics documentation

---

docs/admin/config/batch_changes.mdx

Documentation for https://linear.app/sourcegraph/issue/SRCH-1920/batch-changes-featured-batch-specs

feat(batches): docs for batch spec library labels

---

src/components/Layout.tsx
src/components/TopBanner.tsx

Fixed top banner overlap issue

---

docs/cody/enterprise/completions-configuration.mdx

docs: fix supported models link in Vertex AI example

---

docs/code_insights/explanations/current_limitations_of_code_insights.mdx
docs/code_insights/references/requirements.mdx

Update Code Insights documentation for the changes introduced in [PR 5187](https://github.com/sourcegraph/sourcegraph/pull/5187), which will be in the May 28th (6.4) release.

Update Code Insights docs with new sub-repo perms setting

---

docs/admin/code_hosts/aws_codecommit.mdx
docs/admin/code_hosts/azuredevops.mdx
docs/admin/code_hosts/bitbucket_cloud.mdx
docs/admin/code_hosts/bitbucket_server.mdx
docs/admin/code_hosts/gerrit.mdx
docs/admin/code_hosts/github.mdx
docs/admin/code_hosts/gitlab.mdx
docs/admin/code_hosts/gitolite.mdx
docs/admin/code_hosts/other.mdx
docs/admin/code_hosts/phabricator.mdx
docs/admin/config/settings.mdx
docs/admin/config/site_config.mdx
docs/admin/repo/perforce.mdx

REL-1076
Adds JSX comment markers around embedded JSON schema sections in documentation files to enable automated schema updates during releases.
These markers identify the start and end boundaries for 13 schema sections across site configuration and code host documentation files. The markers include developer warnings to prevent manual edits and version tracking for audit trails.
This prepares the docs repository for automated schema synchronization from the monorepo during the release process.

Add schema sync markers for automated release updates

---

docs/admin/access_control/service_accounts.mdx

- https://linear.app/sourcegraph/issue/PROD-598/enablement-beta-service-accounts

Service Accounts docs

---

docs/admin/code_hosts/github.mdx

Adds some docs on how to use GitHub Enterprise Apps (i.e. add the GitHub App manually)
Also mention how to set up an app-wide code host connection

GitHub Enterprise Apps docs

---

docs/cody/enterprise/completions-configuration.mdx
docs/cody/enterprise/model-config-examples.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1750891262067969?thread_ts=1750888954.498249&cid=C01DXLN3D0T

Move AWS latency optimization to modelConfigexamples docs

---

docs/admin/code_hosts/aws_codecommit.mdx
docs/admin/code_hosts/gitlab.mdx
docs/admin/config/site_config.mdx
docs/admin/repo/perforce.mdx

Some of the end markers for the schema syncher were in the wrong place

Correct incorrectly placed end tags for schema syncher

---

docs/analytics/index.mdx

Fixup for https://github.com/sourcegraph/docs/pull/1237

analytics: fixup heading levels

---

docs/cody/capabilities/auto-edit.mdx

- https://linear.app/sourcegraph/issue/PROD-597/enablement-ga-auto-edit-in-jetbrains-and-visual-studio

Auto-edit GA for JetBrains and Visual Studio

---

docs/sla/index.mdx

This differentiates between Sourcegraph Code Search support plans with everything else.
Basically:
Code Search Enterprise, Cody Enterprise, Amp Enterprise Premium get 24x5
Amp Individual, Teams, Enterprise get 9x5 support

Update SLAs to add Amp Support

---

docs/admin/code_hosts/aws_codecommit.mdx
docs/admin/code_hosts/azuredevops.mdx
docs/admin/code_hosts/bitbucket_cloud.mdx
docs/admin/code_hosts/bitbucket_server.mdx
docs/admin/code_hosts/gerrit.mdx
docs/admin/code_hosts/github.mdx
docs/admin/code_hosts/gitlab.mdx
docs/admin/code_hosts/gitolite.mdx
docs/admin/code_hosts/other.mdx
docs/admin/code_hosts/phabricator.mdx
docs/admin/config/settings.mdx
docs/admin/config/site_config.mdx
docs/admin/repo/perforce.mdx

This PR updates the embedded JSON schemas to match the schemas from Sourcegraph v6.5.1211.
- Updates JSON schema files referenced in MDX documentation
- Maintains version consistency between code and documentation
This PR was created automatically by the schema sync tool during the v6.5.1211 release process.
/cc @sourcegraph/release

Update JSON schemas for v6.5.1211

---

src/data/redirects.ts

We moved it but the product deep links to the old location.
Test plan: CI.

Add redirect from old to new deep search URL

---

docs/cloud/index.mdx

Cloud supports configuring instant audit logs streaming to AWS S3 bucket.
Works instantly on internal instance:

Cloud LogPush: supports s3 destination

---

docs/admin/permissions/api.mdx

Update doc to mention email case sensitivity for Graphql usage

---

docs/cloud/index.mdx
docs/cloud/logpush_gcs.mdx
docs/cloud/logpush_s3.mdx

cloud: update logpush docs

---

docs/analytics/index.mdx

Fix metric description: lines -> characters

---

docs/admin/code_hosts/aws_codecommit.mdx
docs/admin/code_hosts/azuredevops.mdx
docs/admin/code_hosts/bitbucket_cloud.mdx
docs/admin/code_hosts/bitbucket_server.mdx
docs/admin/code_hosts/gerrit.mdx
docs/admin/code_hosts/github.mdx
docs/admin/code_hosts/gitlab.mdx
docs/admin/code_hosts/gitolite.mdx
docs/admin/code_hosts/other.mdx
docs/admin/code_hosts/phabricator.mdx
docs/admin/config/settings.mdx
docs/admin/config/site_config.mdx
docs/admin/repo/perforce.mdx

This PR updates the embedded JSON schemas to match the schemas from Sourcegraph v6.6.0.
- Updates JSON schema files referenced in MDX documentation
- Maintains version consistency between code and documentation
This PR was created automatically by the schema sync tool during the v6.6.0 release process.
/cc @sourcegraph/release

Update JSON schemas for v6.6.0

---

docs/analytics/api.mdx

Reverts sourcegraph/docs#1284
Temporary until we figure out SAT enablement: https://sourcegraph.slack.com/archives/C06358CMSRM/p1753978693642839?thread_ts=1753973156.343589&cid=C06358CMSRM

Revert "Updated cody analytics cookie name to SAMS cookie"

---

docs/cody/capabilities/supported-models.mdx

Changing the docs to reflect recent changes in Cody Gateway.  The preview models have been deprecated by Google. 
We recently swapped our models from: 
- Gemini Pro 2.5 Preview
- Gemini Flash 2.5 Preview
To: 
- Gemini Pro 2.5 
- Gemini Flash 2.5
** Additionally, I removed the "experimental" word from Gemini 2.5 Flash
I ran the dev page on localhost to check the changes.

Updating our Support LLMs page: gemini pro 2.5 preview, gemini flash 2.5 preview -> gemini pro 2.5, gemini flash 2.5

---

src/components/Hero.tsx

Amp-Thread-ID: https://ampcode.com/threads/T-a6e2fde5-e679-4df3-8ec5-856fe3db8df4

Remove Learn about Cody and Code Search buttons from Hero component

---

docs/admin/access_control/index.mdx
docs/admin/config/batch_changes.mdx
docs/admin/config/email.mdx
docs/admin/config/network-filtering.mdx
docs/admin/config/site_config.mdx

1. Versioning callouts in versioned docs don't make sense.
2. Some markdown formatting mistakes.
Test plan: CI.

chore: Some minor docs cleanup

---

docs/cody/core-concepts/token-limits.mdx

Documenting the feature flag is important for customers to understand that they can take advantage of enhanced context limits. I added this section to the Cody Input and Output Limits page to reflect how the feature flag enables larger context windows for various models supported by Sourcegraph.
•	Enhanced context windows require the enhanced-context-window feature flag to be enabled
•	Available since Sourcegraph 6.5 for Enterprise customers
•	Input: Claude/Gemini up to 150k, OpenAI GPT up to 102k, OpenAI o-series up to 93k
•	Output: Claude 64k, Gemini 65k, OpenAI GPT 16k, OpenAI o-series 100k, Reasoning models 100k
Testing: Ran docs locally, confirmed everything looks good

Add Enhanced Context Windows documentation for Cody Token Limits docs page

---

docs/cody/enterprise/model-configuration.mdx

See https://www.notion.so/sourcegraph/3581c98de162436096af66dd474c6ea3#263a8e1126588049bceadd7377e2d3b8 and https://sourcegraph.slack.com/archives/C05GJPTSZCZ/p1757109608671939?thread_ts=1755766102.317339&cid=C05GJPTSZCZ
Amp-Thread-ID: https://ampcode.com/threads/T-8e0b81d8-65e2-48dc-89c0-a18fa7c91fba

cody: document long context for BYOK only

---

docs/deep-search/api.mdx
docs/deep-search/index.mdx
pnpm-lock.yaml
src/data/navigation.ts

Adds docs for the deepsearch API based off of the [internal notion docs](https://www.notion.so/sourcegraph/Deep-Search-API-Usage-253a8e1126588064868ff50143196b7e#253a8e1126588064868ff50143196b7e)

docs(deep search): Add docs for deepsearch API

---

docs/admin/index.mdx
docs/admin/telemetry/index.mdx

Issue:
The last paragraph of the [Telemetry page](https://sourcegraph.com/docs/admin/telemetry) contains two broken links that point to legacy docs. 
This PR removes the paragraph and replaces it with a sentence directing users to contact support for more information about telemetry.
Additionally, I noticed that customers could only find the telemetry from the search bar or the technical changelog. So I added a link to the telemetry page in the list of admin resources on /docs/admin.
Tested it by running local dev

Removed broken links on Telemetry page - added link to admin page

---

docs/api/mcp/index.mdx
docs/deep-search/api.mdx

Adds callout for 1 minute synchronous Deep Search API timeout and removes Deep Search from the list of Sourcegraph MCP tools.

docs(sourcegraph): Document deep search timeout and remove deep search from mcp docs

---

docs/admin/code_hosts/github.mdx

On our docs, **Admin -> Cody Host -> Github**, in the section [Personal Access Tokens,](https://sourcegraph.com/docs/admin/code_hosts/github#personal-access-token-scopes) we have a broken link on the text "(learn more)" 
This section had a broken link pointing to this path: 
https://sourcegraph.com/docs/batch_changes/explanations/permissions_in_batch_changes#code-host-interactions-in-batch-changes
I've updated it to point to:
https://sourcegraph.com/docs/batch-changes/permissions-in-batch-changes#code-host-interactions-in-batch-changes
Tested on local env

Updated a link on point to code-host-interactions-in-batch-changes

---

docs/deep-search/api.mdx

I've verified the examples provided are accurate.

Remove sync API for Deep Search

---

docs/admin/executors/deploy_executors_kubernetes.mdx

Fix SSBC executor broken links 
