sourcegraph/docs

docs/admin/observability/alerting.mdx

Couple minor edits to clarify some points that customer admins get tripped up from time to time.

Updating alerting docs

---

docs/admin/deploy/docker-compose/aws.mdx
docs/admin/deploy/docker-compose/azure.mdx
docs/admin/deploy/docker-compose/digitalocean.mdx
docs/admin/deploy/docker-compose/google_cloud.mdx
docs/admin/deploy/docker-compose/index.mdx
docs/admin/deploy/docker-single-container/aws.mdx
docs/admin/deploy/docker-single-container/digitalocean.mdx
docs/admin/deploy/docker-single-container/google_cloud.mdx
docs/admin/deploy/docker-single-container/index.mdx
docs/admin/deploy/kubernetes/helm.mdx
docs/admin/deploy/machine-images/gce.mdx
docs/admin/executors/deploy_executors_kubernetes.mdx
docs/admin/external_services/postgres.mdx
docs/admin/external_services/redis.mdx
docs/admin/http_https_configuration.mdx
docs/admin/ssl_https_self_signed_cert_nginx.mdx
docs/admin/updates/docker_compose.mdx
docs/admin/updates/pure_docker.mdx
docs/admin/updates/server.mdx

recreating release 5.2.6 doc updates from:
https://github.com/sourcegraph/sourcegraph/pull/59504
Note: this PR does not include the doc changes for `doc/admin/observability/alerts.md` from PR 59504

release 5.2.6 doc updates

---

docs/admin/deploy/index.mdx
docs/admin/deploy/machine-images/index.mdx
docs/admin/external_services/index.mdx

Various cleanup & edits of Sourcegraph machine images documentation

Updates to Machine Images documentation

---

docs/CHANGELOG.mdx
docs/admin/deploy/docker-compose/aws.mdx
docs/admin/deploy/docker-compose/azure.mdx
docs/admin/deploy/docker-compose/digitalocean.mdx
docs/admin/deploy/docker-compose/google_cloud.mdx
docs/admin/deploy/docker-compose/index.mdx
docs/admin/deploy/docker-single-container/aws.mdx
docs/admin/deploy/docker-single-container/digitalocean.mdx
docs/admin/deploy/docker-single-container/google_cloud.mdx
docs/admin/deploy/docker-single-container/index.mdx
docs/admin/deploy/kubernetes/helm.mdx
docs/admin/deploy/machine-images/gce.mdx
docs/admin/executors/deploy_executors_kubernetes.mdx
docs/admin/external_services/postgres.mdx
docs/admin/external_services/redis.mdx
docs/admin/http_https_configuration.mdx
docs/admin/ssl_https_self_signed_cert_nginx.mdx
docs/admin/updates/docker_compose.mdx
docs/admin/updates/pure_docker.mdx
docs/admin/updates/server.mdx

This pull request is part of the Sourcegraph 5.2.7 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.2.7)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/59830)
CI checks in this repository should pass, and a manual review should confirm if the generated changes are correct.

release: sourcegraph@5.2.7

---

docs/code-search/queries/language.mdx

This PR adds the Code Search Query Language docs.

Add Search Query Language Reference

---

docs/code-search/queries/language.mdx

This PR improves the formatting for Code Search Language docs.

Improve formatting for Code Search Language docs

---

src/data/navigation.ts

This PR renames Code AI separator to Code Intelligence.

Rename Code AI to Code Intelligence

---

src/data/navigation.ts

Fix nav links for code navigation, code monitoring and code insights

Fix nav links

---

docs/dev/background-information/bazel/faq.mdx

Renaming PR: https://github.com/sourcegraph/sourcegraph/pull/59857

Update docs for crate rename

---

docs/admin/deploy/index.mdx

added link to the install script doc

added link to the install script doc

---

docs/legacy.mdx
src/data/versions.ts

Add legacy versions

---

docs/admin/pings.mdx

https://github.com/sourcegraph/sourcegraph/pull/60347

add external URL to pings docs

---

docs/cody/clients/enable-cody-enterprise.mdx

Reported by https://github.com/sourcegraph/cody/issues/3082
The model identifiers are defined here: https://platform.openai.com/docs/models/overview

Fix Anthropic model version string

---

docs/cody/usage-and-pricing.mdx

The PR adds docs and FAQs for Cody's Pro plan.

Add pricing docs for Pro plan

---

docs/batch_changes/references/batch_spec_yaml_reference.mdx

- https://sourcegraph.slack.com/archives/C064FKRFAM9/p1707510890570089

Fix components in batch spec YAML reference

---

docs/CHANGELOG.mdx
docs/admin/deploy/docker-compose/aws.mdx
docs/admin/deploy/docker-compose/azure.mdx
docs/admin/deploy/docker-compose/digitalocean.mdx
docs/admin/deploy/docker-compose/google_cloud.mdx
docs/admin/deploy/docker-compose/index.mdx
docs/admin/deploy/docker-single-container/aws.mdx
docs/admin/deploy/docker-single-container/digitalocean.mdx
docs/admin/deploy/docker-single-container/google_cloud.mdx
docs/admin/deploy/docker-single-container/index.mdx
docs/admin/deploy/kubernetes/helm.mdx
docs/admin/deploy/machine-images/gce.mdx
docs/admin/executors/deploy_executors_kubernetes.mdx
docs/admin/external_services/postgres.mdx
docs/admin/external_services/redis.mdx
docs/admin/http_https_configuration.mdx
docs/admin/ssl_https_self_signed_cert_nginx.mdx

This pull request is part of the Sourcegraph 5.3.0 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.0)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60032)
CI checks in this repository should pass, and a manual review should confirm if the generated changes are correct.

release: sourcegraph@5.3.0

---

docs/admin/executors/deploy_executors_kubernetes.mdx

revert the change to deploy_executors_kubernets.mdx

---

docs/admin/config/site_config.mdx

update docs for global settings

---

docs/cody/capabilities/ignore-context.mdx
docs/cody/capabilities/index.mdx
docs/cody/core-concepts/index.mdx
docs/cody/index.mdx
src/data/navigation.ts

Adding docs for the experimental Cody Ignore

Adding Docs for Cody Ignore

---

README.md
next.config.js

it works
Click preview link below, you shouldnt' need to append `/docs` at the end.
https://sourcegraph-docs-v2-git-02-17-impro-b5cfb1-sourcegraph-f8c71130.vercel.app/

improve preview experience

---

docs.config.js
next.config.js
src/data/versions.ts
tsconfig.json

This PR fixes the versioned links for the latest SG attached in-app. I have tested the PR so I am merging it.
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1708354712426079

Fix Version links

---

next.config.js

The PR fixes the broken version links for subpaths.
- https://github.com/sourcegraph/docs/pull/106
No plan required for docs.

Fix version links to support subpaths

---

docs/cody/troubleshooting.mdx

This PR adds a troubleshooting method in case Cody does not include files for context.
- https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1708405594132839

Add troubleshooting method for Cody missing Context files

---

docs/CHANGELOG.mdx
docs/admin/deploy/docker-compose/aws.mdx
docs/admin/deploy/docker-compose/azure.mdx
docs/admin/deploy/docker-compose/digitalocean.mdx
docs/admin/deploy/docker-compose/google_cloud.mdx
docs/admin/deploy/docker-compose/index.mdx
docs/admin/deploy/docker-single-container/aws.mdx
docs/admin/deploy/docker-single-container/digitalocean.mdx
docs/admin/deploy/docker-single-container/google_cloud.mdx
docs/admin/deploy/docker-single-container/index.mdx
docs/admin/deploy/kubernetes/helm.mdx
docs/admin/deploy/machine-images/gce.mdx
docs/admin/external_services/postgres.mdx
docs/admin/external_services/redis.mdx
docs/admin/http_https_configuration.mdx
docs/admin/ssl_https_self_signed_cert_nginx.mdx
docs/versioned/5.2/CHANGELOG.mdx
docs/versioned/5.2/admin/deploy/docker-single-container/aws.mdx
docs/versioned/5.2/admin/deploy/docker-single-container/digitalocean.mdx
docs/versioned/5.2/admin/deploy/docker-single-container/google_cloud.mdx
docs/versioned/5.2/admin/deploy/docker-single-container/index.mdx
docs/versioned/5.2/admin/external_services/postgres.mdx
docs/versioned/5.2/admin/external_services/redis.mdx
docs/versioned/5.2/admin/http_https_configuration.mdx
docs/versioned/5.2/admin/ssl_https_self_signed_cert_nginx.mdx

This pull request is part of the Sourcegraph 5.3.1 release.
* [Release batch change](https://sourcegraph.sourcegraph.com/organizations/sourcegraph/batch-changes/release-sourcegraph-5.3.1)
* [Tracking issue](https://github.com/sourcegraph/sourcegraph/issues/60691)
CI checks in this repository should pass, and a manual review should confirm if the generated changes are correct.

release: sourcegraph@5.3.1

---

src/data/redirects.ts

@MaedahBatool I've tested this locally and it works, but before adding the rest of the missing doc bits, I wanted to check with you. 
Please see the comments in the code directly.

Add missing redirects for generated docs

---

src/data/navigation.ts

This PR removes the portions of docs content that isn't relevant and does not fit well in the navigation.

Remove embeddings and use case section from docs

---

docs/admin/auth/index.mdx
docs/admin/auth/saml/azure_ad.mdx
docs/admin/auth/saml/generic.mdx
docs/admin/auth/saml/index.mdx
docs/admin/scim.mdx
docs/dev/background-information/scim_api.mdx

Reported here: https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1709716403810229
The only remaining mention is in the site config, where I haven't changed it because we pattern match on the string in the backend.

chore: Rename Azure AD -> Entra ID

---

docs/admin/auth/saml/index.mdx

Alongside https://github.com/sourcegraph/sourcegraph/pull/60603
Updates the docs with the added configuration key.

Add SAML docs entry for usernameKeys

---

docs/cody/clients/enable-cody-enterprise.mdx

Correct the link to the lower secion

Fix link to 3rd party llm

---

.github/workflows/pr-auditor.yml

Updating PR auditor to include the SKIP_CHECK_REVIEW_FOR_USERS

Add SKIP_CHECK_REVIEW_FOR_USERS to pr-auditor

---

docs/cody/troubleshooting.mdx

The PR adds troubleshooting docs for recording performance traces for Cody in the VS Code extension.
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1709823019865039

Record performances traces for Cody in VS Code extension

---

docs/cody/faq.mdx

The PR adds an FAQ regarding Cody's support for private and GPL-licensed code. 
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1709760264845289

Add FAQ about Cody supporting license for private and GPL code

---

src/components/search/docsearch/Results.tsx

Adds search result styling for "content" type results which are slightly different than the title-based results

Add rendering for content type search results

---

docs/cody/clients/install-vscode.mdx

The PR adds docs for Cody chat, commands, and autocomplete support with Ollama. 
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1709942321505269

Add docs for Cody support with Ollama

---

docs/cody/clients/install-vscode.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1710269915360359?thread_ts=1709942321.505269&cid=C01DXLN3D0T

Fix Cody Ollama VS Code docs

---

docs/cody/clients/enable-cody-enterprise.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1710203342097449

Add banner for no license checks for Guardrails

---

docs/cody/capabilities/chat.mdx
docs/versioned/5.2/cody/capabilities/chat.mdx

The PR add mention of Cody @, @# abilities from versioned docs and to main docs

Add mention of `@` and `@#` in Cody chat capabilities

---

docs/tutorials/index.mdx

Adding Cody, updating broken links, reorganizing content

Updates to tutorials page

---

docs/admin/config/site_config.mdx

- Changes to the documentation based on:
- Issue: https://github.com/sourcegraph/sourcegraph/issues/36691
- PR: https://github.com/sourcegraph/sourcegraph/pull/60761

docs(admin): update site config docs to include the new displayLimit search limit parameter

---

docs/cody/core-concepts/index.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1710864625457399

Fix tiles and descriptions on Cody Core Concepts index page

---

docs/cody/core-concepts/index.mdx
src/data/navigation.ts

- https://sourcegraph.slack.com/archives/C05MW2TMYAV/p1710865310191839?thread_ts=1710861315.078029&cid=C05MW2TMYAV

Rmv Code Graph page from nav

---

docs/admin/external_service/github.mdx

This was a question on Slack and it took me a bit of digging to find the answer, so adding it to docs for convenience.

Document permissions requested by GitHub app

---

docs/cody/clients/install-jetbrains.mdx

@MaedahBatool if you think a screenshot would be useful (I don't know if we need it), I've attached an example here.

Update sign-in instructions for JB extension

---

src/components/Layout.tsx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1711568680767989

Fix GitHub link in the top header

---

docs/cody/clients/enable-cody-enterprise.mdx

Update the enterprise architecture diagram for Cody Gateway to remove GPT autocomplete from the Gateway-specific diagram.

Fix Cody Gateway architecture diagram - update models.

---

docs/cloud/index.mdx

pick https://github.com/sourcegraph/sourcegraph/pull/59562

update cloud docs

---

src/app/layout.tsx

Update meta tags on sourcegraph.com/docs
- Title tag: Sourcegraph docs
- Meta description: Delve into Sourcegraph Docs to transform your coding workflow. With features like AI-assisted code comprehension with Cody, robust code search across branches, and code intelligence for navigation and insights, streamline your development process for efficiency and accuracy
[SG Issue](https://github.com/sourcegraph/about/issues/6801)
[GitStart Ticket](https://clients.gitstart.com/sourcegraph/ticket/SGM-6801)
- Run the app
- Check the title and the description

SGM-6801 - Update meta tags on sourcegraph.com/docs

---

docs/cody/clients/feature-reference.mdx

Add updates for dynamic multi-line completion, edit command, ask Cody to fix command, and test command (inline vs chat)

Update feature parity matrix

---

src/data/navigation.ts

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1712248035256419?thread_ts=1712181108.851529&cid=C01DXLN3D0T

Move Feature Parity Reference under Cody Capabilities

---

docs/admin/config/settings.mdx

Docs for https://github.com/sourcegraph/sourcegraph/pull/61338

Expand notices configuration

---

docs/cody/core-concepts/context.mdx
docs/cody/core-concepts/token-limits.mdx
src/data/navigation.ts

Adds specific doc page on token limits

Cody Input and Output Token Limits

---

docs/cloud/private_connectivity_sourcegraph_connect.mdx

cloud: update src connect docs

---

docs/CHANGELOG.mdx

Changelog update.
[Context](https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1712820582025739?thread_ts=1712635157.963189&cid=C04MSD3DP5L)

5.3.9104 changelog update

---

docs/admin/auth/index.mdx
docs/admin/external_service/github.mdx

Minor wording changes to clarify docs based on recent support tickets which caused confusion

Morgan updates0415

---

docs/code-search/queries/index.mdx
docs/code-search/queries/language.mdx

Including how it affects Batch Changes,
Code Monitors, and Code Insights.

Add info about keyword search

---

docs/CHANGELOG.mdx

release: 5.3.11625 changelog update

---

docs/CHANGELOG.mdx

5.3.12303 changelog update

---

docs/CHANGELOG.mdx

changelog: fix markdown headers

---

docs/admin/deploy/docker-compose/aws.mdx
docs/admin/deploy/docker-compose/azure.mdx
docs/admin/deploy/docker-compose/digitalocean.mdx
docs/admin/deploy/docker-compose/google_cloud.mdx
docs/admin/deploy/docker-compose/index.mdx
docs/admin/deploy/instance-size.mdx
docs/admin/deploy/kubernetes/index.mdx
docs/admin/deploy/kubernetes/scale.mdx
docs/admin/deploy/resource_estimator.mdx
docs/admin/deployment_best_practices.mdx
docs/admin/enterprise_getting_started_guide/index.mdx
docs/admin/how-to/repo-not-updated.mdx
docs/admin/how-to/site-admin-quickstart.mdx
docs/admin/observability/outbound-request-log.mdx
docs/admin/observability/troubleshooting.mdx
docs/code-search/features.mdx
src/components/MdxComponents.tsx
src/components/resource-estimator/ResourceEstimator.tsx
src/styles/tailwind.css

This PR adds the Resource Estimator docs. It includes the newly-built React component for the ResourceEstimator.tsx file that integrates the calculator in the MDX file.

Add resource estimator

---

docs/cody/clients/feature-reference.mdx

The PR adds a newly created version of the Feature Parity Reference for all Cody Clients on different platforms and plans. 
- https://docs.google.com/spreadsheets/d/1u_llQtSqMmPZIm0pea8mfsucxG5VBYj-H_48waOvWpY/edit#gid=0
- https://sourcegraph-docs-v2-git-feature-parity-new-sourcegraph-f8c71130.vercel.app/cody/clients/feature-reference

Updated version of Cody Feature Parity Reference

---

docs/cody/clients/index.mdx

Fix links to product link cards.

Ship improvements to Cody clients index page

---

docs/admin/beta_and_experimental_features.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1714707307202909

Fix ToC formatting in Beta features docs

---

docs/admin/config/site_config.mdx
docs/versioned/5.2/admin/config/site_config.mdx

Fix discrepancy between address field in 
https://sourcegraph.com/docs/admin/config/site_config
https://sourcegraph.com/docs/admin/observability/alerting#alerting
Updated link 1 to match link 2(correct)

Update observability alerts email

---

docs/CHANGELOG.mdx

changelog update

---

src/components/Navigation.tsx
src/components/PrevNextLinks.tsx
src/data/navigation.ts

Implemented navigation versions to manage distinct navigational structures for different docs versions.

Added version navigations

---

docs/cody/capabilities/supported-models.mdx
docs/cody/clients/feature-reference.mdx
docs/cody/clients/install-vscode.mdx

Docs for VS Code release 1.18.

Add docs for VS Code 1.18 release

---

docs/code-search/index.mdx
docs/code-search/types/fuzzy.mdx
docs/index.mdx
docs/versioned/5.2/code-search/index.mdx
docs/versioned/5.2/code-search/types/fuzzy.mdx
docs/versioned/5.2/index.mdx
docs/versioned/5.3/code-search/index.mdx
docs/versioned/5.3/code-search/types/fuzzy.mdx
docs/versioned/5.3/index.mdx

fix links to old github discussions (point to new community.sourcegraph.com)

---

docs/cody/index.mdx
docs/versioned/5.2/cody/index.mdx
docs/versioned/5.3/cody/index.mdx

Fix GitHub Discussions link in Cody docs

---

docs/cody/clients/install-vscode.mdx

Add how to change models

---

docs/cody/clients/install-vscode.mdx

Added Alt option to instructions

Fix chat instructions to change models

---

docs/cody/capabilities/chat.mdx
docs/cody/index.mdx

Updates Cody docs for the new Cody messaging outlined in Notion.

Update Cody messaging in docs

---

docs/CHANGELOG.mdx

Closes https://linear.app/sourcegraph/issue/REL-68/update-changelog-website-when-all-changes-are-accounted-for

Update changelog for 5.4.2198

---

contentlayer.config.ts
package.json
pnpm-lock.yaml
src/app/[...slug]/page.tsx
src/components/CopyButton.tsx
src/components/MdxComponents.tsx
src/components/PreCodeBlock.tsx

- Added a copy button for code blocks that allows users to easily copy code snippets from MDX code blocks with a single click.
- Fixed table overflow issue

Added copy code feature for mdx code blocks

---

docs/admin/deploy/kubernetes/operations.mdx

Add codeinsights-db to backup operations list

---

docs/admin/deploy/docker-compose/operations.mdx

Add codeinsights db to backup and restore operations for docker compose

---

docs/admin/updates/index.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1717009830340849

Remove mentions of Helm from our Upgrading guide

---

docs/admin/deploy/docker-compose/configuration.mdx
docs/admin/deploy/docker-compose/index.mdx
docs/admin/deploy/kubernetes/configure.mdx
docs/admin/deploy/kubernetes/index.mdx
docs/admin/deploy/kubernetes/kustomize.mdx
docs/cody/core-concepts/index.mdx

Removed references to deprecated embeddings service and associated configuration

Embeddings configuration docs cleanup

---

docs/cody/clients/install-vscode.mdx
docs/cody/quickstart.mdx

With the new VS Code release this PR adds all new docs.

Add new docs for UX changes in VS Code

---

docs/cody/capabilities/supported-models.mdx

Source: https://github.com/sourcegraph/cody/blob/main/lib/shared/src/models/dotcom.ts

Remove the deprecated Claude models from the list of supported models

---

docs/cody/capabilities/ignore-context.mdx

- https://sourcegraph.slack.com/archives/C02FSM7DU/p1717528132453369?thread_ts=1717527605.976099&cid=C02FSM7DU

Fix code indendation in Context Filters docs

---

docs/admin/deploy/kubernetes/index.mdx
docs/admin/deploy/kubernetes/kustomize.mdx
docs/admin/deployment_best_practices.mdx
docs/admin/index.mdx
docs/cli/quickstart.mdx
docs/cli/references/index.mdx
docs/cody/clients/enable-cody-enterprise.mdx

- Updated AWS Bedrock enterprise Cody configuration documentation
- Cleanup of administration landing page
- Minor updates to k8s deploy page headers for clarity
- Minor formatting updates for CLI pages

Misc docs updates

---

docs/cody/capabilities/supported-models.mdx

Added ChatGPT-4o support for enterprise.mdx

---

docs/cody/clients/index.mdx

removed exclamation mark for VS Code

---

docs/cody/capabilities/commands.mdx

Update typo in cody user settings file

---

docs/releases.mdx

Update docs to reflect new version in table.
Reformat tables for proper alignment
Use `latest` URL so URL doesn't have to be updated in future.

docs: update release page for 5.4.5099 release

---

docs/cody/core-concepts/token-limits.mdx

Update token-limits for ENT

---

docs/cody/clients/enable-cody-enterprise.mdx

Update smartContextWindow SG version number

---

src/components/Logo.tsx

- Fixed the issue with the logo for the dev and preview environments.

Fixed logo path issue

---

src/components/Logo.tsx

Revert "Fixed logo path issue"

---

docs/cody/capabilities/supported-models.mdx

Revert "Update supported-models.mdx"

---

docs/admin/auth/saml/index.mdx

Simple FAQ entry for a question we had regarding multiple X509 certificates.

Add FAQ entry for SAML multiple certs

---

docs/CHANGELOG.mdx

mdx doesn't like unescaped curly braces. Will have to patch the changelog tool. 

fix(changelog): escape curly braces in changelog

---

src/data/redirects.ts

Reduce routes

---

next.config.js

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1718311577703929

Fix versions redirects

---

docs/legacy.mdx

Add 5.2 and 5.3 to legacy versions page

---

next.config.js

Add new redirect for versions

---

next.config.js

Add new redirect for versions @5.3

---

src/app/sitemap.ts

Added a sitemap file. It can be accessed by visiting '/sitemap.xml'.

Added sitemap

---

docs/cody/clients/feature-reference.mdx

https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1718912888456369?thread_ts=1718655286.227469&cid=C01DXLN3D0T

fix multi-repo context mentions

---

src/components/Toc.tsx
src/components/icons/BugIcon.tsx
src/components/icons/PencilIcon.tsx

Added feedback option.

---

docs/batch-changes/bulk-operations-on-changesets.mdx
docs/batch-changes/configuring-credentials.mdx
docs/batch-changes/create-a-batch-change.mdx
docs/batch-changes/delete-a-batch-change.mdx
docs/batch-changes/publishing-changesets.mdx
docs/batch-changes/quickstart.mdx
docs/batch-changes/tracking-existing-changesets.mdx
docs/batch-changes/update-a-batch-change.mdx

This updates screenshots and video assets for Batch Changes docs. A lot of the UI has changed since most of these docs were written, this is an update to that.

update screenshots and videos for batch changes doc

---

docs/integration/vscode/index.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1719339505007949

Fix broken links

---

docs/cody/usage-and-pricing.mdx

Small change on how to get to the cancellation screen

change steps on how to get to cody dashboard

---

docs/admin/auth/login_form.mdx

Add docs for SSO sign-in with perms syncing

---

docs/cody/core-concepts/context.mdx

Fixed some wording in the Cody Context page.

Fix wording in Cody context

---

docs/cody/clients/enable-cody-enterprise.mdx

[Linear Issue ](https://linear.app/sourcegraph/issue/CODY-2650/docs-needed)
[Linear Issue
](https://linear.app/sourcegraph/issue/CODY-2660/update-the-llm-supported-doc)

Adding documentation for GCP vertex AI with anthropic models

---

docs/cody/clients/enable-cody-enterprise.mdx

Added Claude 3.5 Sonnet to supported models

updated smartcontextwindow docs

---

docs/cody/clients/feature-reference.mdx

Update LLM selection in Cody Free feature parity matrix

---

docs/cody/clients/install-jetbrains.mdx

- https://sourcegraph.slack.com/archives/C04MZPE4JKD/p1720034205308869?thread_ts=1719509675.420099&cid=C04MZPE4JKD

Update LLM Selection Models on JetBrains

---

docs/admin/deploy/kubernetes/index.mdx

Warn users that Autopilot clusters are not supported.

Warn users that Autopilot clusters are not supported.

---

docs/batch-changes/batch-spec-yaml-reference.mdx
docs/batch-changes/create-a-batch-change.mdx
docs/batch-changes/quickstart.mdx

This adds documentation for the new batch spec version.
Relates to https://github.com/sourcegraph/sourcegraph/pull/63613

batches: document new version field

---

docs/own/index.mdx

Fixing typo in ownership doc

---

docs/releases.mdx

Clarifying to prevent confusion about releasing new patches for old releases.

Clarify release support

---

docs/admin/code_hosts/aws_codecommit.mdx

This update fixes a small typo in step 1 of adding CodeCommit repos in a Docker container.

Fix typo in CodeCommit SSH Connection section

---

docs/cody/capabilities/supported-models.mdx

Remove the default model for free users as both pro and free users have access to multiple models.

Update supported-models page

---

docs/admin/permissions/syncing.mdx

Update typo in syncing.mdx

---

docs/cody/usage-and-pricing.mdx

FAQ - how to access invoices

---

docs/batch-changes/faq.mdx

Reference to Batch Change Ownership change procedure

---

docs/cody/clients/feature-reference.mdx

Remove `Expanded Context Window for Claude 3` from feature matrix

Remove `Expanded Context Window for Claude 3` from feature matrix

---

docs/cody/clients/install-jetbrains.mdx

Rmv LLM drop down from JB

---

docs/cody/clients/index.mdx
docs/cody/clients/install-cli.mdx
src/data/navigation.ts

Fixes https://linear.app/sourcegraph/issue/CODY-2659/document-cody-cli-on-docssourcegraphcom
Previously, the Cody CLI was documented in a readme file here. As part of our effort to make the CLI a more polished product, this PR adds new documentation on how to install and use Cody CLI that will be available at the URL https://docs.sourcegraph.com/cody/clients/install-cli
I tried to find a color that works OK in both light and dark theme.
Dark             |  Light
:-------------------------:|:-------------------------:

CLI: add documentation for Cody CLI

---

docs/cody/clients/cody-with-sourcegraph.mdx

Just a link change to point directly to cody web

Change link to cody web

---

docs/cody/clients/enable-cody-enterprise.mdx

Direct ENT docs CTA link to Sales Page

---

docs/cody/core-concepts/token-limits.mdx

Add clarity in Token Limits docs

---

docs/cody/capabilities/chat.mdx
docs/cody/capabilities/commands.mdx
docs/cody/clients/install-vscode.mdx
docs/cody/quickstart.mdx
src/components/MdxComponents.tsx

This PR adds changes to docs regarding the new experience with the unified Cody panel with Sourcegraph VS Code July release.

Add docs for VS Code v1.28

---

docs/cody/clients/install-jetbrains.mdx

Add instructions on changing to stable or nightly on jetbrains

---

docs/admin/code_hosts/aws_codecommit.mdx

This PR adds important information related to use of AWS IAM Roles as an alternative to tokens and username and password options. IAM roles are currently in the development pipeline so we expect this to change in the near term future,

Callout banner for best practice IAM roles

---

docs/admin/updates/index.mdx

Include links for Helm standard/multi-version Upgrade and AWS AMI

Add AMI and Helm to Upgrade types

---

docs/admin/search.mdx

Relates to https://github.com/sourcegraph/zoekt/pull/798

search: update shard merging with latest changes

---

docs/admin/repo/perforce.mdx

Just a short explanation on the Perforce page on when labels are converted to tags.

Add docs explaining Perforce labels

---

docs/releases.mdx

Update the docs to refer to the latest Sourcegraph release.

(fix) update docs page with latest release

---

docs/cody/clients/enable-cody-enterprise.mdx

Changing enterprise contact sales cta

Changing enterprise contact sales cta

---

docs/admin/repo/metadata.mdx
docs/code-search/queries/language.mdx

Add docs for new metadata regex feature

---

docs/cody/clients/install-vscode.mdx

Update removing account instructions on VSCode

---

docs/cody/clients/install-vscode.mdx

Add keyboard shortcuts

---

docs/code-search/working/saved_searches.mdx

This PR updates the Saved Searches docs. 
- https://linear.app/sourcegraph/issue/SRCH-786/update-saved-searches-docs

Docs for Saved Searches for the Aug release

---

README.md
docs.config.js
docs/admin/repo/metadata.mdx
docs/admin/repo/perforce.mdx
docs/admin/search.mdx
docs/code-search/queries/language.mdx
docs/code-search/working/saved_searches.mdx
docs/cody/capabilities/commands.mdx
docs/cody/capabilities/ignore-context.mdx
docs/cody/clients/cody-with-sourcegraph.mdx
docs/cody/clients/feature-reference.mdx
docs/cody/clients/install-jetbrains.mdx
docs/cody/clients/install-vscode.mdx
docs/cody/index.mdx
docs/cody/quickstart.mdx
docs/legacy.mdx
next.config.js
src/components/MdxComponents.tsx
src/data/navigation.ts
src/data/versions.ts

This is the docs working branch for the August 7th release. PMs, ENG and all the project DRIs please add all your docs contributions to this branch and ping me for review.

Docs working branch for the August 7th release

---

docs/code-search/features.mdx

This PR adds docs about the new Code Search experience that is live with Sourcegraph version 5.6.0 and more.

Add docs about the new Code Search experience

---

docs/cody/clients/install-vscode.mdx

Change to how to open a chat window on VSCode

---

docs/releases.mdx

Links in the release page didn't go to the exact release notes. Add `v` in the URL fixes this.

fix(docs): Add 'v' to notes URLs for links to specific versions

---

docs/code-search/features.mdx

The PR adds more details about the feature flags to our Code Search Features docs. There are details for the new Search UI for our admins.
- https://sourcegraph.slack.com/archives/C05EA9KQUTA/p1723211552096099

Add more details about the new Search UI

---

docs/admin/code_hosts/bitbucket_server.mdx

Add note about personal repositories for Bitbucket Server

---

docs/admin/auth/index.mdx
docs/admin/code_hosts/bitbucket_server.mdx
docs/admin/permissions/index.mdx

Docs for https://github.com/sourcegraph/sourcegraph/pull/64179

Add docs for Bitbucket Server OAuth

---

docs/admin/code_hosts/aws_codecommit.mdx

This update makes a change to this doc to capture the correct status of our provisions as referenced by https://linear.app/sourcegraph/issue/SRC-513/support-aws-iam-roles-for-codecommit-with-assumerole

Update CodeCommit Callout

---

docs/admin/deploy/docker-compose/index.mdx

Small formatting fix to the anchor link formatting.

Docker Compose docs - fix anchor link formatting

---

next.config.js

Make version paths dynamic for latest and old versions.

📦 NEW: Working redirects

---

docs/admin/pings.mdx

Updating pings docs to include that we collect ip address of the instance (`remote_ip` in pings)

Update `pings.mdx` to include collection of ip address

---

docs/admin/scim.mdx

Add Okta SCIM private provisioning callout

---

docs/batch-changes/configuring-credentials.mdx

Follow-up to https://github.com/sourcegraph/sourcegraph/pull/64496

docs(batches): add experimental label to gh apps; explain that updates are currently not possible

---

docs/cody/clients/install-jetbrains.mdx

Docs for inline fix in JetBrains

---

docs/admin/repo/perforce.mdx

Add small note to perforce p4.port docs

---

docs/admin/deploy/machine-images/aws-ami.mdx

Add note for Auto-upgrade state being unsupported for AMI instances

Add note for Auto-upgrade unsupported for AMI instances

---

docs/cody/clients/model-configuration.mdx

- https://sourcegraph.slack.com/archives/C05A5R7NQUX/p1724282914231849?thread_ts=1724221561.516719&cid=C05A5R7NQUX

Add EAP notice for model configuration

---

docs/batch-changes/configuring-credentials.mdx

Based on https://sourcegraph.slack.com/archives/C012V43N8E7/p1724928676289499?thread_ts=1723741990.954679&cid=C012V43N8E7
For https://linear.app/sourcegraph/issue/SRCH-946/how-do-we-handle-open-batch-changes-when-switching-authentication

docs(batches): explain credential migration

---

docs/admin/updates/index.mdx

Fix screenshot on update sourcegraph page

---

README.md

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1725037409559779

Update link in readme to add images/videos

---

docs/sla/index.mdx

We no longer offer Slack Account Management as a Support package

Remove Slack Acct Mgmt as an option

---

docs/admin/pricing.mdx

update billing definition to include rejection of autocompletion events

Update billing active user definition to include rejected autocompletion events

---

docs/CHANGELOG.mdx

This is an automated changelog update for v5.7.0

Changelog for v5.7.0

---

docs/releases.mdx

Update the release page for 5.7 release

Update release page for 5.7 release

---

docs/releases.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1725558197389579

Remove get SG button from releases docs

---

docs/CHANGELOG.mdx

Fix formatting in change log table of contents 

(chore)docs: fix-changelog-toc

---

docs/admin/index.mdx
docs/admin/updates/index.mdx

Add some rewording to the main deployment landing page.

Clean up entrypoint for Deploy and Upgrade

---

docs/code_insights/how-tos/index.mdx

Add link to insight troubleshooting page

---

docs/code-search/code-navigation/how-to/index.mdx

This page was 404ing
https://sourcegraph.com/docs/code-search/code-navigation/how-to

Add index for code nav how-to page

---

src/data/navigation.ts

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1726034799066249

Navigate Changelog link in docs to new website

---

docs/admin/deploy/machine-images/aws-ami.mdx

MVU are not supported so link was confusing, and link pointed to the upgrade notes page anyways.

Remove link for "multi-version upgrades" from AMI upgrade docs

---

docs/releases.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1726217490079989

Fix formatting on releases page

---

package.json
pnpm-lock.yaml
src/components/mdx/CustomLink.tsx
src/components/ui/hoverCard.tsx

Added hover card for more context

---

docs/releases.mdx

- Update docs for the latest Sourcegraph Release.
- Put customer facing naming back in place

Update docs for latest release

---

docs/cody/faq.mdx

Makes the FAQ around non-programming questions point to our AUP.
Motivation: https://sourcegraph.slack.com/archives/C07CNJTGB3Q/p1727024986089139

Point non-programming FAQ question to AUP

---

docs/admin/code_hosts/aws_codecommit.mdx
docs/admin/repo/auth.mdx

Update ssh repo clone docs

---

docs/cody/faq.mdx

This update introduces an answer to a question where users would like to find out if they can use a model of choice to chat with Cody on CLI.

Add FAQ for using model of preference on Cody CLI

---

docs/cody/capabilities/chat.mdx
docs/cody/clients/install-jetbrains.mdx
docs/cody/core-concepts/context.mdx
docs/cody/core-concepts/embeddings.mdx
docs/cody/core-concepts/index.mdx
docs/cody/core-concepts/keyword-search.mdx
docs/cody/faq.mdx
docs/cody/troubleshooting.mdx
docs/cody/usage-and-pricing.mdx

The PR removes complete mentions about mentions of Embeddings from Cody's docs.
- https://sourcegraph.slack.com/archives/C05AGQYD528/p1727282487703709

Remove mentions of Embeddings from Cody docs

---

docs/admin/deploy/docker-compose/upgrade.mdx

- https://sourcegraph.com/docs/admin/deploy/docker-compose/upgrade
- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1727992212723339

Fix 500 server error docker-compose/upgrade docs

---

docs/releases.mdx

The PR updates releases page for v5.8

Update releases page for 5.8

---

docs/cloud/index.mdx
docs/cloud/private_connectivity_aws.mdx
docs/cloud/private_connectivity_gcp.mdx
docs/cloud/private_connectivity_public_lb.mdx
docs/cloud/private_connectivity_sourcegraph_connect.mdx

various grammar and spelling fixes to improve the readability of our cloud docs

Cloud doc readability updates

---

docs/releases.mdx

Release page was showing wrong versions after recent a recent commit. Reverted the commit and updated the latest version.

fix(docs): fix release versions

---

docs/technical-changelog.mdx

The PR updates the page title and description of the technical changelog page.

Update page title and description of Technical Changelog

---

docs/releases.mdx

Update latest Sourcegraph version in docs

Update latest sourcegraph version

---

src/components/PreCodeBlock.tsx

Fixed syntax highlight issue

---

docs/cody/capabilities/autocomplete.mdx
docs/cody/faq.mdx
docs/index.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1729701612053759

Improve docs for Cody Autocomplete

---

.github/pull_request_template.md

Update PR approval template

---

docs/releases.mdx

Update releases page for `5.9.0` release

chore(docs): Update latest version

---

docs/cody/capabilities/commands.mdx
docs/cody/capabilities/debug-code.mdx
docs/cody/capabilities/openctx.mdx
docs/cody/capabilities/supported-models.mdx
docs/cody/core-concepts/context.mdx
docs/cody/index.mdx
src/components/MdxComponents.tsx

Add more improvements

---

docs/releases.mdx

We should only merge this in once the release is completed. 
The [Releases notion page](https://www.notion.so/sourcegraph/Sourcegraph-Releases-eee2a5384b0a4555adb51b439ddde35f?pvs=4) should also be updated to include this, maybe?

rel: Include Sourcegraph 5 Release 9 Patch 1 in releases.mdx

---

docs/technical-changelog.mdx

There were a bunch of left overs from the PR template in the changelog itself. 

chore(rel): cleanup optional headings in changelog

---

docs/admin/pricing.mdx

I missed the link, adding a callout will make sure others don't do the same

Add callout component

---

docs/cody/index.mdx

Hackathon - Cody

---

docs/admin/auth/builtin.mdx

Follow up to [this discussion](https://sourcegraph.slack.com/archives/C05EMJM2SLR/p1731436302493959)

Adds header to make it more clear how to disable account requests

---

docs/cody/capabilities/supported-models.mdx

Hackathon - Supported Models

---

src/data/navigation.ts

Remove old versioned navigation items

Remove old versioned navigation items

---

src/components/mdx/CustomLink.tsx

Updated hover card for text

---

baseai/memory/docs/index.ts

Improve LB docs memory

---

docs/releases.mdx

Fix broken links after technical changelog page was renamed (again?).

fix(docs): update links in release page

---

docs/admin/config/advanced_config_file.mdx

Update broken link to sourcegraph/sourcegraph

Update link to schema

---

docs/technical-changelog.mdx

Fix a couple of spelling mistakes in the changelog.

Fix spelling mistakes

---

docs/code-search/queries/examples.mdx

Added link to more regex examples

Update examples.mdx to include link to more regex examples

---

docs/cody/quickstart.mdx

Remove "the Cody"

---

docs/admin/postgres.mdx

capitalize postgres

---

docs/admin/postgres.mdx
docs/releases.mdx
docs/technical-changelog.mdx

Fix patch number in changelog, add to latest release listing.

fix(rel): fix patch number, add Postgres notice

---

docs/admin/observability/metrics.mdx

Clarifying the different approaches for new vs existing instances.

Updating Grafana security details

---

docs/releases.mdx
docs/technical-changelog.mdx

This is an automated changelog update for v5.11.0

Changelog for v5.11.0

---

docs/releases.mdx
docs/technical-changelog.mdx

Fix some terminal output that ended up in the changelog somehow. 

fix(docs): fix terminal output that ended up in changelog

---

docs/batch-changes/batch-spec-cheat-sheet.mdx

Replaced the cat-based approach with a direct input redirection method using `while IFS= read -r`. This change ensures proper handling of the last line which doesn't have a trailing new line.

Update 'loop over paths in file' example

---

docs/api/stream_api/index.mdx

Resolves https://linear.app/sourcegraph/issue/SPLF-789/indeed-question-about-stream-api-qualifier#comment-666293e1

Clarify stream API format qualifying note

---

docs/code-search/index.mdx

Fix grammatical error in index.mdx

---

docs/admin/updates/kubernetes.mdx

fixed broken link

---

docs/cody/clients/install-eclipse.mdx

Add feedback link to forum on install-eclipse.mdx

---

docs/admin/audit_log.mdx
docs/cloud/index.mdx

cloud: clean up audit logs docs

---

docs/admin/postgres.mdx

Update dead link in Postgres docs to external Postgres provider.

chore(docs): update dead link in Postgres docs

---

docs/admin/deploy/machine-images/aws-oneclick.mdx

Remove reference to install script

chore(docs): remove ref to single image

---

docs/admin/deploy/index.mdx

Add better description for the best use case of machine images. Highlight strengths and weaknesses.

chore(docs): add better description for machine image use case

---

src/components/mdx/Tabs.tsx

This PR removes the outline border from the Tabs component.

Remove border from the Tabs component

---

docs/admin/config/webhooks/incoming.mdx

Correcting webhook logging example

---

docs/analytics/index.mdx

Update screenshot of cloud Sourcegraph Analytics

---

docs/admin/enterprise_getting_started_guide/index.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1738352746632029

SG enterprise docs resources

---

docs/sla/index.mdx

Add Enterprise Starter SLA

---

docs/admin/permissions/index.mdx

Label perforce as beta not experimental

Label perforce as beta not experimental

---

docs/pricing/enterprise-starter.mdx

Removing omnibox terminology and replacing with intention detect + integrated search results

remove-omnibox-term

---

baseai/memory/docs/index.ts

🐛 FIX: memory config

---

baseai/memory/docs/index.ts
package.json
pnpm-lock.yaml
scripts/llms-txt-generator.js

📦 NEW: memory deployed and llms.txt generator

---

docs/cody/core-concepts/cody-gateway.mdx

correct link to list of supported LLMs

Fixed link cody-gateway.mdx

---

docs/admin/observability/alerts.mdx

Update alerts docs

---

docs/technical-changelog.mdx

This is an automated changelog update for v6.0.2687

Changelog for v6.0.2687

---

docs/releases.mdx
docs/technical-changelog.mdx

This is an automated changelog update for v6.1.0

Changelog for v6.1.0

---

docs/cody/clients/install-cli.mdx

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1739903695056049

Remove mentions of Cody CLI support for Free and Pro

---

docs/cody/clients/install-visual-studio.mdx

states minimum version of VS for autocomplete to work

update minimum version in VS

---

docs/cody/prompts-guide.mdx

Related to https://github.com/sourcegraph/cody/pull/7118, this PR updates docs to inform users that they need to index their repositories before they can @ mention local repos for context.
Follow up PR to update the in product CTA to this section

update @mention CTA for Enterprise users

---

docs/cloud/index.mdx

cloud: clarify managed settings

---

docs/cloud/index.mdx

cloud: fix sla link

---

docs/code-search/features.mdx

- https://github.com/sourcegraph/docs/pull/1048

Docs for personalized search rankings

---

README.md

- https://sourcegraph.slack.com/archives/C89KCDK5J/p1744057628570389

Update readme about previewing docs URLs

---

src/app/chat.tsx

Fix path /docs in bot in prod

---

src/components/ChatBot/styles.css

Fix bot button styles light/dark modes

---

src/components/ChatBot/styles.css

Revert "Fix bot button styles light/dark modes"

---

package.json
pnpm-lock.yaml

This PR fixes the AI chatbot submit button color. Currently the app styles are overwriting submit button styles.

🐛 FIX: AI chatbot submit button bg color

---

docs/admin/deploy/index.mdx

fix(rel): update speellin'

---

README.md

Just made a small fix in the Readme

🐛 FIX: Small fix in readme

---

docs/admin/subscriptions/index.mdx

@enriquegh @michaellzc it'd be great to direct them to how to restart the front-end service if we have that in another page. My update look alright?
Add note setting expectations on licensing

licensing-note

---

baseai/memory/memory-sg-docs-live/index.ts

Update LB memory for APR22

---

docs/legacy.mdx
pnpm-lock.yaml
src/data/versions.ts

- https://sourcegraph.slack.com/archives/C01DXLN3D0T/p1745503697479829

Fix legacy versions

---

docs/cody/usage-and-pricing.mdx
docs/pricing/faqs.mdx
docs/pricing/plans/enterprise-starter.mdx

- Add new FAQ explaining how to access invoices
- Clarify in both Cody and Enterprise Starter docs that invoices are not emailed monthly
- Ensure consistent information across documentation

docs: add information about invoice access

---

docs/pricing/faqs.mdx

Note that a section of our pricing faq only applies to Cody, not search etc

Note that section only applies to cody

---

docs/cody/capabilities/chat.mdx
docs/cody/capabilities/supported-models.mdx

- https://linear.app/sourcegraph/issue/PROD-555/faster-smart-apply-ga-gtm-enablement

Faster Smart Apply updates

---

docs/code-search/compare-file-filtering.mdx
docs/code-search/features.mdx

- https://linear.app/sourcegraph/issue/PROD-572/compare-page-file-filtering-ui-ga-gtm-enablement

Add file and directory filtering on compare page

---

docs/admin/observability/index.mdx

Update contact info in observability page

---

docs/admin/deploy/machine-images/aws-ami.mdx

Fix AMI image upload

---

docs/admin/config/private-network.mdx

Follow up to https://github.com/sourcegraph/docs/pull/987

update NO_PROXY recommendations

---

docs/cody/prompts-guide.mdx

Fix typo in prompts-guide

---

docs/cody/clients/feature-reference.mdx

Fix extra spacing

---

docs/cody/capabilities/openctx.mdx

Add MCP as recommended protocol for fetching context

---

docs/cody/capabilities/supported-models.mdx

…ing Cody gateway
Update docs - add how to enable Claude models for smart apply when using Cody gateway

Update docs - add how to enable Claude models for smart apply when using Cody gateway

---

src/components/Layout.tsx

Rmv OpenCtx banner

---

scripts/llms-txt-generator.js

Update script. Remove changelog content

Update llms.txt file

---

src/components/Layout.tsx

Comment out banner temporarily

---

docs/analytics/index.mdx

Adding blurb to mention that ES customers also get access to Sourcegraph Analytics

add ES to Sourcegraph Analytics offering

---

docs/analytics/index.mdx

Ah, another oopsie from me, sorry

analytics: fixup screenshot position

---

src/data/navigation.ts

Missed a spot, this still says "cloud analytics"

analytics: fixup left nav

---

docs/cloud/index.mdx

Cloud exposed new region for customers today - https://sourcegraph.slack.com/archives/C03JR7S7KRP/p1751468128881399
This is just update in the docs.

Cloud: new region Saudi Arabia

---

docs/sla/index.mdx

Clarify 24x7 Support plan name

---

docs/technical-changelog.mdx

This change is a quick fix for a broken changelog release in `v6.7.1104`

quick fix changelog for 6.7.x family

---

docs/cody/capabilities/supported-models.mdx

add gpt-5 models to supported models page

Add support for GPT-5 models in documentation
